create or replace view SFDC.PUBLIC.APPLICATION_DETAILS(
	"Opportunity Name",
	"Account Name",
	"DBA Name",
	"Agreemnet Number",
	"Application Date",
	"Approval Date",
	"Approval Expiration Date",
	"Contracts In Date",
	"Funded Date",
	"Write Off Date",
	"Contract In Date",
	"Contract Out Date",
	"Due Diligence Date",
	"Processing Date",
	"Decline Date",
	"UW Decision Date",
	"Type",
	"Opportunity Record Type",
	"Industry",
	"Industry Vertical",
	"State of Business Registration",
	"Business Entity Type",
	"Billing State",
	"Billing City",
	"Billing Postal Code",
	"Opportunity Stage",
	"Strategic PartnerID",
	"Gross Annual Sales",
	"Maximum Approval",
	"Years_In_Business__c",
	"Rate Factor",
	"Paymnet Amount",
	"Paymnet Frequency",
	"Funded Amount",
	"Interest Amount",
	"Term",
	"Repayment Amount",
	"Extension Total",
	"Installment Amount Collected",
	"Days Money Out",
	"Discount RTR From Early Repayment",
	"Open Balance",
	"Repayment Status",
	"Pacing",
	"Total Write Off",
	"Total Failed Paymnets",
	"First Payment Date",
	"First Failed Paymnet Date",
	"Last Failed Paymnet Date",
	"Next Paymnet Due Date",
	"OpportunityId",
	"ApplicationId",
	"AccountId",
	"RepaymnetId",
	"Is Early Repayment Executed",
	"Is Funded",
	"Funded Sequence",
	"Is Repeat Deal",
	"Early Repayment Total Collected",
	"Is Write Off",
	"Original Margin",
	"Primary Owner FICO",
	"Last Payment Received Date",
	"Duration Days",
	"Origination Fee Assessed",
	"Open Principal Balance",
	"Is Active Unit",
	"Write Off Principal",
	"Sales Rep Id",
	"Lead_Vintage__c",
	"Monthly_Rate_Factor__c",
	"Sales Rep Name",
	"Original Sales Rep",
	"Original Renewal Rep",
	"Monthly Margin",
	"Submission Type",
	"Underwriter Name",
	"Partner Name",
	"Processor Name",
	"Total RTR Amount Paid",
	"Weekly Payment Amount - Contractual",
	"Weekly Payment Amount - Current",
	"Count of Expected Payments",
	"Total Expected Payments - Contractual",
	"Total Expected Payments - Current",
	"Auto-Approval",
	"Number of Applicants",
	"Approval Available Amount",
	"Deal Stage",
	"Previous ApplicationId",
	"App to Approval Days",
	"App to Approval Hours",
	"Approve to Funded",
	"App to Funded",
	"App to Processed Hours",
	"App to Decision Hours",
	"Contract In to Due Diligence"
) COMMENT='The table contains records of business opportunities, specifically applications, submitted by companies. Each record represents a single application and includes details about the opportunity, company, and industry.'
 as
  WITH
  "Applications" AS (
    SELECT
      "Id" AS "Id_Application",
      "Name",
      "Application_Status__c",
      "Approval_Date__c",
      "Approval_Expiration_Date__c",
      "Approved_Amount__c",
      "Approved_Duration__c",
      "Approved_Payment_Frequency__c",
      "Average_Daily_Sales__c",
      "Gross_Annual_Sales__c",
      "Opportunity__c",
      "SOS_Date__c",
      "Decline_Reason__c",
      "Adverse_Action_Date__c",
      "Adverse_Action_Type__c",
      "Application_In_Date__c",
      "Past_Auto_Close_Date__c",
      "Master_Approval_Amount__c",
      "Corp_Only__c",
      "Average_Monthly_Sales__c",
      "Underwriter__c",
      "Test_Record__c",
      "State_Past_Due_Taxes__c",
      "Federal_Past_Due_Taxes__c",
      "SOS_Including_Status__c",
      "Account__c",
      "Approval_Exception__c",
      "Approval_Amount__c",
      "Approval_Depleted_Amount__c",
      "Approval_Status__c",
      "Submission_Type__c",
      "Approval_Available_Amount__c",
      "Approval_Exception_Description__c",
      "Processor__c",
      "Opportunity_Num_Contact_Roles__c"
    FROM
      "SFDC"."STAGE"."FC_APPLICATION__C"
  ),
  "Opportunity_w_AppId" AS (
    SELECT
      *
    FROM
      (
        SELECT
          A."Id" AS "Id_Application",
          IFF(A."Opportunity__c" = O."Id", 0, 1) "Auto-Approval",
          "AccountId" "OpportunityAccountId",
          O.*,
          ROW_NUMBER() OVER (
            PARTITION BY
              O."Id"
            ORDER BY
              O."Id",
              A."Approval_Date__c" DESC
          ) AS "RNO"
        FROM
          SFDC.STAGE."OPPORTUNITY" O
          LEFT JOIN SFDC.STAGE."FC_APPLICATION__C" A ON O."Id" = A."Opportunity__c"
          OR O."Approval_Application__c" = A."Id"
        WHERE
          O."Test_Record__c" = FALSE
          AND O."Application_In_Date__c" IS NOT NULL
      ) AS "JoinedData"
    WHERE
      "RNO" = 1
  ),
  "Opps_w_Apps" AS (
    SELECT
      LHS.*,
      RHS."Id_Application" AS "Id_Application_RHS",
      RHS."Name" AS "Name_RHS",
      RHS."Application_Status__c",
      RHS."Approval_Date__c" AS "Approval_Date__c_RHS",
      RHS."Approval_Expiration_Date__c" AS "Approval_Expiration_Date__c_RHS",
      RHS."Approved_Amount__c",
      RHS."Approved_Duration__c",
      RHS."Approved_Payment_Frequency__c" AS "Approved_Payment_Frequency__c_RHS",
      RHS."Average_Daily_Sales__c",
      RHS."Gross_Annual_Sales__c" AS "Gross_Annual_Sales__c_RHS",
      RHS."Opportunity__c",
      RHS."SOS_Date__c",
      RHS."Decline_Reason__c",
      RHS."Adverse_Action_Date__c",
      RHS."Adverse_Action_Type__c",
      RHS."Application_In_Date__c" AS "Application_In_Date__c_RHS",
      RHS."Past_Auto_Close_Date__c",
      RHS."Master_Approval_Amount__c",
      RHS."Corp_Only__c" AS "Corp_Only__c_RHS",
      RHS."Average_Monthly_Sales__c" AS "Average_Monthly_Sales__c_RHS",
      RHS."Underwriter__c",
      RHS."Test_Record__c" AS "Test_Record__c_RHS",
      RHS."State_Past_Due_Taxes__c",
      RHS."Federal_Past_Due_Taxes__c",
      RHS."SOS_Including_Status__c",
      RHS."Account__c",
      RHS."Approval_Exception__c",
      RHS."Approval_Amount__c",
      RHS."Approval_Depleted_Amount__c",
      RHS."Approval_Status__c",
      RHS."Submission_Type__c",
      RHS."Approval_Available_Amount__c",
      RHS."Approval_Exception_Description__c",
      RHS."Processor__c",
      RHS."Opportunity_Num_Contact_Roles__c",
    FROM
      "Opportunity_w_AppId" LHS
      LEFT OUTER JOIN "Applications" RHS ON LHS."Id_Application" = RHS."Id_Application"
  ),
  "Users" AS (
    SELECT
      "Id" AS "Id_User",
      "Name" AS "Sales Rep Name"
    FROM
      "SFDC"."STAGE"."USER"
  ),
  "PIVOT" AS (
    WITH
      "AGG" AS (
        SELECT
          "OpportunityId" AS "OpportunityId",
          "TeamMemberRole" AS "TeamMemberRole",
          ANY_VALUE("UserId") AS "ANY_UserId_aggTable"
        FROM
          "SFDC"."STAGE"."OPPORTUNITYTEAMMEMBER"
        WHERE
          "TeamMemberRole" IN ('Renewal Rep', 'Sales Rep')
        GROUP BY
          "OpportunityId",
          "TeamMemberRole"
      )
    SELECT
      "OpportunityId",
      MAX(
        IFF(
          "TeamMemberRole" = 'Renewal Rep',
          "ANY_UserId_aggTable",
          NULL
        )
      ) AS "Renewal Rep_ANY_UserId",
      MAX(
        IFF(
          "TeamMemberRole" = 'Sales Rep',
          "ANY_UserId_aggTable",
          NULL
        )
      ) AS "Sales Rep_ANY_UserId"
    FROM
      "AGG"
    GROUP BY
      "OpportunityId"
  ),
  "MANAGE COLUMNS_op0" AS (
    SELECT
      "Id",
      "RecordTypeId",
      "CreatedDate",
      "LastModifiedDate",
      "cmbls__Repayment__c",
      "cmbls__ACH_Batch__c",
      "cmbls__ACH_Processor__c",
      "cmbls__Account_Lookup__c",
      "cmbls__Account__c",
      "cmbls__Actual_Merchant_Payment_Amount__c",
      "cmbls__Add_to_Reserve__c",
      "cmbls__Addenda__c",
      "cmbls__Additional_Fee_Amortization_Date__c",
      "cmbls__Amount_Applied_to_Advance__c",
      "cmbls__Amount_Applied_to_Draw_Reserve__c",
      "cmbls__Amount_Applied_to_Draw__c",
      "cmbls__Amount_Applied_to_Fees__c",
      "cmbls__Amount_Applied_to_Lender_Reimbursement__c",
      "cmbls__Amount_Applied_to_Reserve__c",
      "cmbls__Amount_Received_from_Borrower__c",
      "cmbls__Applied_to_Cash_Collateral__c",
      "cmbls__Applied_to_Deferred_Fees__c",
      "cmbls__Applied_to_Escrow_Reserve__c",
      "cmbls__Applied_to_Interest_Reserve__c",
      "cmbls__Auto_Generated__c",
      "cmbls__Balance__c",
      "cmbls__Check__c",
      "cmbls__Count_of_Transactions_on_Repayment__c",
      "cmbls__Deduct_from_Reserve__c",
      "cmbls__Draw__c",
      "cmbls__Effective_Date__c",
      "cmbls__Error_Code__c",
      "cmbls__Error_Description__c",
      "cmbls__External_Transaction_ID__c",
      "cmbls__Fail_Date__c",
      "cmbls__Fee_Collected__c",
      "cmbls__Fee_Settings_Created__c",
      "cmbls__Fees__c",
      "cmbls__Funding_Payment__c",
      "cmbls__Holdback_Amount__c",
      "cmbls__Holdback__c",
      "cmbls__InterestAccrual__c",
      "cmbls__Interest_Amortization_Date__c",
      "cmbls__Interest_Payment_Amt__c",
      "cmbls__Interest_Payment_Percent__c",
      "cmbls__Is_Payment__c",
      "cmbls__Is_Post_Write_Off_Date__c",
      "cmbls__Is_Running_Balance_Applicable__c",
      "cmbls__Lender_s_Fee_to_Outside_Lender_Amount__c",
      "cmbls__Lender_s_Fee_to_Outside_Lender__c",
      "cmbls__Lender_s_Net_Amount__c",
      "cmbls__Lender_s_Portion_Percentage__c",
      "cmbls__Manual_Allocation__c",
      "cmbls__Memo__c",
      "cmbls__Merchant_Id__c",
      "cmbls__Merchant_Name__c",
      "cmbls__Merchant_Total_Amount__c",
      "cmbls__Merchant_Total_Holdback__c",
      "cmbls__NSF_Count__c",
      "cmbls__Notes__c",
      "cmbls__Omit_From_Invoice__c",
      "cmbls__Omit_from_Open_Balance__c",
      "cmbls__Original_Invoice_Line_Item__c",
      "cmbls__Original_Invoice__c",
      "cmbls__Original_Scheduled_Date__c",
      "cmbls__Paid_Back__c",
      "cmbls__Payment_Amount_Formula__c",
      "cmbls__Payment_Amount__c",
      "cmbls__Payment_Method__c",
      "cmbls__Payment_Number__c",
      "cmbls__Payment_Type__c",
      "cmbls__Payment__c",
      "cmbls__Payoff__c",
      "cmbls__Post_Write_Off_Record__c",
      "cmbls__Posted_to_accounting__c",
      "cmbls__Principal_Payment_Amt__c",
      "cmbls__Principal_Payment_Percent__c",
      "cmbls__Process_Date__c",
      "cmbls__Processed_Amount__c",
      "cmbls__Processor_Integration__c",
      "cmbls__Repayment_Schedule__c",
      "cmbls__Reserve_Deducted__c",
      "cmbls__Reserve_Payment_Amount__c",
      "cmbls__Response_Code_Count__c",
      "cmbls__Response_Code__c",
      "cmbls__Resubmitted_Of__c",
      "cmbls__Reversal_Created__c",
      "cmbls__Reversal_Of__c",
      "cmbls__Running_Balance__c",
      "cmbls__Running_Balance_on_Interest__c",
      "cmbls__Running_Balance_on_Principal__c",
      "cmbls__Running_Principal_Balance_Number__c",
      "cmbls__Running_Principal_Balance__c",
      "cmbls__Sequence__c",
      "cmbls__Settlement_Date__c",
      "cmbls__Settlement_Id__c",
      "cmbls__Split_Batch__c",
      "cmbls__Status_Amount__c",
      "cmbls__Status_Image__c",
      "cmbls__Status__c",
      "cmbls__Sub_Type__c",
      "cmbls__System_Notes__c",
      "cmbls__Transaction_Amount__c",
      "cmbls__Transaction_Type__c",
      "cmbls__Type_of_Account__c",
      "cmbls__Disbursed__c",
      "cmbls__Repaid__c",
      "cmbls__Scheduled_From_Portal__c",
      "Refund_Disbursement__c",
      "cmbls__Amount_Applied_to_Overcollection_Reserve__c",
      "cmbls__Disbursement__c",
      "cmbls__Original_Fund__c",
      "cmbls__Payoff_Selected_Loan_Status__c",
      "cmbls__Payoff_Selected_Remaining_Allocation__c",
      "cmbls__Pending_Payment_Loan_Transfer__c",
      "ACH_Processor_Cash_Account_GL_Num__c",
      "Collection_of_Processing_Fee_Desc__c",
      "FRPSA_Processing_Fee_Receivable_Desc__c",
      "Payment_FRPSA_Fee_Income_Desc__c",
      "Payment_FRPSA_Receivable_Desc__c",
      "Payment_Repayment_of_Loan_Desc__c",
      "Servicing_Fee_Servicing_Fee_Income_Desc__c",
      "Servicing_Fee_Servicing_Fee_Rec_Desc__c",
      "Settlement_Date_Formula__c",
      "Allowance_for_Bad_Debt__c",
      "FRPSA_Fee_Income_GL_Num__c",
      "FRPSA_Processing_Fee_GL_Num__c",
      "Receivable_GL_Number__c",
      "GL_Fix__c",
      "Failed_Payment_Resolved__c",
      "cmbls__Extra_Principal_Amount__c",
      "Processing_Fee_Booking_Credit_GL__c",
      "Processing_Fee_Booking_Debit_GL__c",
      "Processing_Fee_Collection_Debit_GL__c",
      "Processing_Fee_Collection_Credit_GL__c",
      "Early_Repay_Discount_Debit_GL__c",
      "Funding_Disbursement_GL__c",
      "Funding_Receivable_GL__c",
      "cmbsa__Amount_Paid_to_Syndicators__c",
      "cmbsa__Generate_Payables__c",
      "cmbsa__Payables_Not_Created__c",
      "cmbsa__Reason_for_Payables_Not_Created__c",
      "cmbsa__Reasons_for_Payables_Not_Created__c",
      "cmbsa__Syndicators_Fee__c",
      "cmbsa__Update_Failed_Payables__c",
      "cmbsa__Amount_Kept_by_Lender__c",
      "Amount_Payable_to_Syndicators__c",
      "Actual_Transaction_Amount__c",
      "Effective_Date_Aligned__c",
      "Failed_Payment__c",
      "Repayment_Next_Hit_Date__c",
      "Restoration_Status_Date__c",
      "Restoration_Status__c",
      "Num_Days_Past_Due__c",
      "cmbls__Amount_Applied_to_Overcollection_Formula__c"
    FROM
      "SFDC"."STAGE"."CMBLS__PAYMENT__C"
  ),
  "Opps_w_Rep" AS (
    SELECT
      LHS.*,
      RHS."Id_User",
      RHS."Sales Rep Name"
    FROM
      "Opps_w_Apps" LHS
      LEFT OUTER JOIN "Users" RHS ON LHS."OwnerId" = RHS."Id_User"
  ),
  "Sales Team Members" AS (
    SELECT
      PIVOT."OpportunityId" "OppTeamMemberId",
      U1."Sales Rep Name" AS "New Sales Rep Team Member",
      U2."Sales Rep Name" AS "Renew Sales Rep Team Member"
    FROM
      PIVOT
      LEFT JOIN "Users" AS U1 ON PIVOT."Sales Rep_ANY_UserId" = U1."Id_User"
      LEFT JOIN "Users" AS U2 ON PIVOT."Renewal Rep_ANY_UserId" = U2."Id_User"
  ),
  "MANAGE COLUMNS" AS (
    SELECT
      "Id" AS "Id",
      "RecordTypeId" AS "RecordTypeId",
      "CreatedDate" AS "CreatedDate",
      "LastModifiedDate" AS "LastModifiedDate",
      "cmbls__Repayment__c" AS "cmbls__Repayment__c",
      "cmbls__ACH_Batch__c" AS "cmbls__ACH_Batch__c",
      "cmbls__ACH_Processor__c" AS "cmbls__ACH_Processor__c",
      "cmbls__Account_Lookup__c" AS "cmbls__Account_Lookup__c",
      "cmbls__Account__c" AS "cmbls__Account__c",
      "cmbls__Actual_Merchant_Payment_Amount__c" AS "cmbls__Actual_Merchant_Payment_Amount__c",
      "cmbls__Add_to_Reserve__c" AS "cmbls__Add_to_Reserve__c",
      "cmbls__Addenda__c" AS "cmbls__Addenda__c",
      "cmbls__Additional_Fee_Amortization_Date__c" AS "cmbls__Additional_Fee_Amortization_Date__c",
      "cmbls__Amount_Applied_to_Advance__c" AS "cmbls__Amount_Applied_to_Advance__c",
      "cmbls__Amount_Applied_to_Draw_Reserve__c" AS "cmbls__Amount_Applied_to_Draw_Reserve__c",
      "cmbls__Amount_Applied_to_Draw__c" AS "cmbls__Amount_Applied_to_Draw__c",
      "cmbls__Amount_Applied_to_Fees__c" AS "cmbls__Amount_Applied_to_Fees__c",
      "cmbls__Amount_Applied_to_Lender_Reimbursement__c" AS "cmbls__Amount_Applied_to_Lender_Reimbursement__c",
      "cmbls__Amount_Applied_to_Reserve__c" AS "cmbls__Amount_Applied_to_Reserve__c",
      "cmbls__Amount_Received_from_Borrower__c" AS "cmbls__Amount_Received_from_Borrower__c",
      "cmbls__Applied_to_Cash_Collateral__c" AS "cmbls__Applied_to_Cash_Collateral__c",
      "cmbls__Applied_to_Deferred_Fees__c" AS "cmbls__Applied_to_Deferred_Fees__c",
      "cmbls__Applied_to_Escrow_Reserve__c" AS "cmbls__Applied_to_Escrow_Reserve__c",
      "cmbls__Applied_to_Interest_Reserve__c" AS "cmbls__Applied_to_Interest_Reserve__c",
      "cmbls__Auto_Generated__c" AS "cmbls__Auto_Generated__c",
      "cmbls__Balance__c" AS "cmbls__Balance__c",
      "cmbls__Check__c" AS "cmbls__Check__c",
      "cmbls__Count_of_Transactions_on_Repayment__c" AS "cmbls__Count_of_Transactions_on_Repayment__c",
      "cmbls__Deduct_from_Reserve__c" AS "cmbls__Deduct_from_Reserve__c",
      "cmbls__Draw__c" AS "cmbls__Draw__c",
      "cmbls__Effective_Date__c" AS "cmbls__Effective_Date__c",
      "cmbls__Error_Code__c" AS "cmbls__Error_Code__c",
      "cmbls__Error_Description__c" AS "cmbls__Error_Description__c",
      "cmbls__External_Transaction_ID__c" AS "cmbls__External_Transaction_ID__c",
      "cmbls__Fail_Date__c" AS "cmbls__Fail_Date__c",
      "cmbls__Fee_Collected__c" AS "cmbls__Fee_Collected__c",
      "cmbls__Fee_Settings_Created__c" AS "cmbls__Fee_Settings_Created__c",
      "cmbls__Fees__c" AS "cmbls__Fees__c",
      "cmbls__Funding_Payment__c" AS "cmbls__Funding_Payment__c",
      "cmbls__Holdback_Amount__c" AS "cmbls__Holdback_Amount__c",
      "cmbls__Holdback__c" AS "cmbls__Holdback__c",
      "cmbls__InterestAccrual__c" AS "cmbls__InterestAccrual__c",
      "cmbls__Interest_Amortization_Date__c" AS "cmbls__Interest_Amortization_Date__c",
      "cmbls__Interest_Payment_Amt__c" AS "cmbls__Interest_Payment_Amt__c",
      "cmbls__Interest_Payment_Percent__c" AS "cmbls__Interest_Payment_Percent__c",
      "cmbls__Is_Payment__c" AS "cmbls__Is_Payment__c",
      "cmbls__Is_Post_Write_Off_Date__c" AS "cmbls__Is_Post_Write_Off_Date__c",
      "cmbls__Is_Running_Balance_Applicable__c" AS "cmbls__Is_Running_Balance_Applicable__c",
      "cmbls__Lender_s_Fee_to_Outside_Lender_Amount__c" AS "cmbls__Lender_s_Fee_to_Outside_Lender_Amount__c",
      "cmbls__Lender_s_Fee_to_Outside_Lender__c" AS "cmbls__Lender_s_Fee_to_Outside_Lender__c",
      "cmbls__Lender_s_Net_Amount__c" AS "cmbls__Lender_s_Net_Amount__c",
      "cmbls__Lender_s_Portion_Percentage__c" AS "cmbls__Lender_s_Portion_Percentage__c",
      "cmbls__Manual_Allocation__c" AS "cmbls__Manual_Allocation__c",
      "cmbls__Memo__c" AS "cmbls__Memo__c",
      "cmbls__Merchant_Id__c" AS "cmbls__Merchant_Id__c",
      "cmbls__Merchant_Name__c" AS "cmbls__Merchant_Name__c",
      "cmbls__Merchant_Total_Amount__c" AS "cmbls__Merchant_Total_Amount__c",
      "cmbls__Merchant_Total_Holdback__c" AS "cmbls__Merchant_Total_Holdback__c",
      "cmbls__NSF_Count__c" AS "cmbls__NSF_Count__c",
      "cmbls__Notes__c" AS "cmbls__Notes__c",
      "cmbls__Omit_From_Invoice__c" AS "cmbls__Omit_From_Invoice__c",
      "cmbls__Omit_from_Open_Balance__c" AS "cmbls__Omit_from_Open_Balance__c",
      "cmbls__Original_Invoice_Line_Item__c" AS "cmbls__Original_Invoice_Line_Item__c",
      "cmbls__Original_Invoice__c" AS "cmbls__Original_Invoice__c",
      "cmbls__Original_Scheduled_Date__c" AS "cmbls__Original_Scheduled_Date__c",
      "cmbls__Paid_Back__c" AS "cmbls__Paid_Back__c",
      "cmbls__Payment_Amount_Formula__c" AS "cmbls__Payment_Amount_Formula__c",
      "cmbls__Payment_Amount__c" AS "cmbls__Payment_Amount__c",
      "cmbls__Payment_Method__c" AS "cmbls__Payment_Method__c",
      "cmbls__Payment_Number__c" AS "cmbls__Payment_Number__c",
      "cmbls__Payment_Type__c" AS "cmbls__Payment_Type__c",
      "cmbls__Payment__c" AS "cmbls__Payment__c",
      "cmbls__Payoff__c" AS "cmbls__Payoff__c",
      "cmbls__Post_Write_Off_Record__c" AS "cmbls__Post_Write_Off_Record__c",
      "cmbls__Posted_to_accounting__c" AS "cmbls__Posted_to_accounting__c",
      "cmbls__Principal_Payment_Amt__c" AS "cmbls__Principal_Payment_Amt__c",
      "cmbls__Principal_Payment_Percent__c" AS "cmbls__Principal_Payment_Percent__c",
      "cmbls__Process_Date__c" AS "cmbls__Process_Date__c",
      "cmbls__Processed_Amount__c" AS "cmbls__Processed_Amount__c",
      "cmbls__Processor_Integration__c" AS "cmbls__Processor_Integration__c",
      "cmbls__Repayment_Schedule__c" AS "cmbls__Repayment_Schedule__c",
      "cmbls__Reserve_Deducted__c" AS "cmbls__Reserve_Deducted__c",
      "cmbls__Reserve_Payment_Amount__c" AS "cmbls__Reserve_Payment_Amount__c",
      "cmbls__Response_Code_Count__c" AS "cmbls__Response_Code_Count__c",
      "cmbls__Response_Code__c" AS "cmbls__Response_Code__c",
      "cmbls__Resubmitted_Of__c" AS "cmbls__Resubmitted_Of__c",
      "cmbls__Reversal_Created__c" AS "cmbls__Reversal_Created__c",
      "cmbls__Reversal_Of__c" AS "cmbls__Reversal_Of__c",
      "cmbls__Running_Balance__c" AS "cmbls__Running_Balance__c",
      "cmbls__Running_Balance_on_Interest__c" AS "cmbls__Running_Balance_on_Interest__c",
      "cmbls__Running_Balance_on_Principal__c" AS "cmbls__Running_Balance_on_Principal__c",
      "cmbls__Running_Principal_Balance_Number__c" AS "cmbls__Running_Principal_Balance_Number__c",
      "cmbls__Running_Principal_Balance__c" AS "cmbls__Running_Principal_Balance__c",
      "cmbls__Sequence__c" AS "cmbls__Sequence__c",
      "cmbls__Settlement_Date__c" AS "cmbls__Settlement_Date__c",
      "cmbls__Settlement_Id__c" AS "cmbls__Settlement_Id__c",
      "cmbls__Split_Batch__c" AS "cmbls__Split_Batch__c",
      "cmbls__Status_Amount__c" AS "cmbls__Status_Amount__c",
      "cmbls__Status_Image__c" AS "cmbls__Status_Image__c",
      "cmbls__Status__c" AS "cmbls__Status__c",
      "cmbls__Sub_Type__c" AS "cmbls__Sub_Type__c",
      "cmbls__System_Notes__c" AS "cmbls__System_Notes__c",
      "cmbls__Transaction_Amount__c" AS "cmbls__Transaction_Amount__c",
      "cmbls__Transaction_Type__c" AS "cmbls__Transaction_Type__c",
      "cmbls__Type_of_Account__c" AS "cmbls__Type_of_Account__c",
      "cmbls__Disbursed__c" AS "cmbls__Disbursed__c",
      "cmbls__Repaid__c" AS "cmbls__Repaid__c",
      "cmbls__Scheduled_From_Portal__c" AS "cmbls__Scheduled_From_Portal__c",
      "Refund_Disbursement__c" AS "Refund_Disbursement__c",
      "cmbls__Amount_Applied_to_Overcollection_Reserve__c" AS "cmbls__Amount_Applied_to_Overcollection_Reserve__c",
      "cmbls__Disbursement__c" AS "cmbls__Disbursement__c",
      "cmbls__Original_Fund__c" AS "cmbls__Original_Fund__c",
      "cmbls__Payoff_Selected_Loan_Status__c" AS "cmbls__Payoff_Selected_Loan_Status__c",
      "cmbls__Payoff_Selected_Remaining_Allocation__c" AS "cmbls__Payoff_Selected_Remaining_Allocation__c",
      "cmbls__Pending_Payment_Loan_Transfer__c" AS "cmbls__Pending_Payment_Loan_Transfer__c",
      "ACH_Processor_Cash_Account_GL_Num__c" AS "ACH_Processor_Cash_Account_GL_Num__c",
      "Collection_of_Processing_Fee_Desc__c" AS "Collection_of_Processing_Fee_Desc__c",
      "FRPSA_Processing_Fee_Receivable_Desc__c" AS "FRPSA_Processing_Fee_Receivable_Desc__c",
      "Payment_FRPSA_Fee_Income_Desc__c" AS "Payment_FRPSA_Fee_Income_Desc__c",
      "Payment_FRPSA_Receivable_Desc__c" AS "Payment_FRPSA_Receivable_Desc__c",
      "Payment_Repayment_of_Loan_Desc__c" AS "Payment_Repayment_of_Loan_Desc__c",
      "Servicing_Fee_Servicing_Fee_Income_Desc__c" AS "Servicing_Fee_Servicing_Fee_Income_Desc__c",
      "Servicing_Fee_Servicing_Fee_Rec_Desc__c" AS "Servicing_Fee_Servicing_Fee_Rec_Desc__c",
      "Settlement_Date_Formula__c" AS "Settlement_Date_Formula__c",
      "Allowance_for_Bad_Debt__c" AS "Allowance_for_Bad_Debt__c",
      "FRPSA_Fee_Income_GL_Num__c" AS "FRPSA_Fee_Income_GL_Num__c",
      "FRPSA_Processing_Fee_GL_Num__c" AS "FRPSA_Processing_Fee_GL_Num__c",
      "Receivable_GL_Number__c" AS "Receivable_GL_Number__c",
      "GL_Fix__c" AS "GL_Fix__c",
      "Failed_Payment_Resolved__c" AS "Failed_Payment_Resolved__c",
      "cmbls__Extra_Principal_Amount__c" AS "cmbls__Extra_Principal_Amount__c",
      "Processing_Fee_Booking_Credit_GL__c" AS "Processing_Fee_Booking_Credit_GL__c",
      "Processing_Fee_Booking_Debit_GL__c" AS "Processing_Fee_Booking_Debit_GL__c",
      "Processing_Fee_Collection_Debit_GL__c" AS "Processing_Fee_Collection_Debit_GL__c",
      "Processing_Fee_Collection_Credit_GL__c" AS "Processing_Fee_Collection_Credit_GL__c",
      "Early_Repay_Discount_Debit_GL__c" AS "Early_Repay_Discount_Debit_GL__c",
      "Funding_Disbursement_GL__c" AS "Funding_Disbursement_GL__c",
      "Funding_Receivable_GL__c" AS "Funding_Receivable_GL__c",
      "cmbsa__Amount_Paid_to_Syndicators__c" AS "cmbsa__Amount_Paid_to_Syndicators__c",
      "cmbsa__Generate_Payables__c" AS "cmbsa__Generate_Payables__c",
      "cmbsa__Payables_Not_Created__c" AS "cmbsa__Payables_Not_Created__c",
      "cmbsa__Reason_for_Payables_Not_Created__c" AS "cmbsa__Reason_for_Payables_Not_Created__c",
      "cmbsa__Reasons_for_Payables_Not_Created__c" AS "cmbsa__Reasons_for_Payables_Not_Created__c",
      "cmbsa__Syndicators_Fee__c" AS "cmbsa__Syndicators_Fee__c",
      "cmbsa__Update_Failed_Payables__c" AS "cmbsa__Update_Failed_Payables__c",
      "cmbsa__Amount_Kept_by_Lender__c" AS "cmbsa__Amount_Kept_by_Lender__c",
      "Amount_Payable_to_Syndicators__c" AS "Amount_Payable_to_Syndicators__c",
      "Actual_Transaction_Amount__c" AS "Actual_Transaction_Amount__c",
      "Effective_Date_Aligned__c" AS "Effective_Date_Aligned__c",
      "Failed_Payment__c" AS "Failed_Payment__c",
      "Repayment_Next_Hit_Date__c" AS "Repayment_Next_Hit_Date__c",
      "Restoration_Status_Date__c" AS "Restoration_Status_Date__c",
      "Restoration_Status__c" AS "Restoration_Status__c",
      "Num_Days_Past_Due__c" AS "Num_Days_Past_Due__c",
      "cmbls__Amount_Applied_to_Overcollection_Formula__c" AS "cmbls__Amount_Applied_to_Overcollection_Formula__c",
      IFF(
        "cmbls__Status__c" = 'Failed'
        AND "cmbls__Payment_Type__c" = 'Payment',
        1,
        0
      ) AS "Failed Payment",
      iff(
        IFF(
          "cmbls__Status__c" = 'Failed'
          AND "cmbls__Payment_Type__c" = 'Payment',
          1,
          0
        ) = 1,
        "cmbls__Effective_Date__c",
        NULL
      ) AS "Failed Payment Date"
    FROM
      "MANAGE COLUMNS_op0"
  ),
  "Accounts" AS (
    SELECT
      "Id",
      "Name",
      "Type",
      "RecordTypeId",
      "ParentId",
      "BillingAddress",
      "ShippingAddress",
      "Phone",
      "Website",
      "Industry",
      "AnnualRevenue",
      "NumberOfEmployees",
      "Description",
      "OwnerId",
      "CreatedDate",
      "CreatedById",
      "LastActivityDate",
      "LastViewedDate",
      "IsPartner",
      "ChannelProgramName",
      "ChannelProgramLevelName",
      "AccountSource",
      "Industry_Vertical__c",
      "Business_Entity_Type__c",
      "State_of_Business_Registration__c",
      "Date_Established__c",
      "cmbls__Email_Address__c",
      "DBA__c",
      "Customer_Id__c",
      "Seed_to_Sale_Software__c",
      "Federal_Tax_Id__c",
      "McaApp__Balance__c",
      "McaApp__Bank_Acct_Nums__c",
      "McaApp__Business_Name__c",
      "McaApp__Business_Phone__c",
      "McaApp__DBA_Name__c",
      "McaApp__Date_Business_Established__c",
      "McaApp__Email__c",
      "McaApp__Federal_Tax_ID_No__c",
      "McaApp__Is_Seasonal__c",
      "McaApp__Lease_start_date__c",
      "McaApp__Legal_Name__c",
      "McaApp__Length_of_Ownership__c",
      "McaApp__MIDs__c",
      "McaApp__Main_Contact__c",
      "McaApp__Monthly_Bank_Deposit_Avg_All__c",
      "McaApp__NumberofLocations__c",
      "McaApp__Owner_1_City__c",
      "McaApp__Payback_Funded__c",
      "McaApp__Property_Type__c",
      "McaApp__State_Of_Incorporation__c",
      "McaApp__Total_Comissions_Amount__c",
      "McaApp__Total_Funded_Amount__c",
      "McaApp__Type_of_Entity__c",
      "McaApp__Years_in_Business__c",
      "McaApp__Count_Of_Opportunities__c",
      "cmbla__ISO_Checklist__c",
      "cmbla__SLAExpirationDate__c",
      "New_Funding_Fee_Example__c",
      "New_Funding_Fee_Percent__c",
      "Renewal_Compensation_Eligibility__c",
      "Renewal_Funding_Fee_Example__c",
      "Renewal_Funding_Fee_Percent__c",
      "Partner_Web_External_Id__c",
      "Strategic_Partner__c",
      "All_Time_Funded_Deal_Count__c",
      "Total_Repaid_Deals__c",
      "Years_In_Business__c",
      "County__c",
      "Initial_Application_In_Date__c",
      "Referral_Contact__c",
      "Approval_Available_Amount__c",
      "Approval_Amount__c",
      "Approval_Depleted_Amount__c",
      "Approval_Expiration_Date__c",
      "Num_Opportunities__c",
      "DOZISF__ZoomInfo_Last_Updated__c",
      "NAICS_Code__c",
      "cmbls__Billing_City_And_State__c",
      "Master_Approval_Amount__c",
      "Master_Approval_Expiration__c",
      "Master_Approval_Status__c",
      "Master_Current_Utilization_Amount__c",
      "Master_Approval_Amount_Available__c",
      "All_Time_Funded_Amount__c",
      "Initial_Funded_Amount__c",
      "Lead_Initial_Create_Date__c",
      "Initial_Lead_Source__c",
      "Initial_Campaign__c",
      "List_Source__c",
      "EID__c",
      "Strategic_Partner_Status__c",
      "cmbsa__Syndicator__c",
      "Commission_Roll_Up__c",
      "Licensed_State__c",
      "Prospect_Status__c",
      "Test_Record__c",
      "n2de__Distribution_count__c",
      "n2de__Distribution_engine_details__c",
      "n2de__Is_distributed__c",
      "n2de__Is_reassigned__c",
      "n2de__Last_distributed__c",
      "n2de__Last_reassigned__c",
      "n2de__Time_to_action_mins__c",
      "Payment_Preference__c",
      "BillingCity",
      "BillingPostalCode",
      "BillingState",
      "BillingStreet"
    FROM
      "SFDC"."STAGE"."ACCOUNT"
  ),
  "Opps_w_TeamMembers" AS (
    SELECT
      LHS.*,
      RHS."OppTeamMemberId",
      RHS."New Sales Rep Team Member",
      RHS."Renew Sales Rep Team Member"
    FROM
      "Opps_w_Rep" LHS
      LEFT OUTER JOIN "Sales Team Members" RHS ON LHS."Id" = RHS."OppTeamMemberId"
  ),
  "Repaymnet" AS (
    SELECT
      "Id",
      "Name",
      "RecordTypeId",
      "CreatedDate",
      "cmbls__Payee_Account__c",
      "cmbls__Accrued_Interest__c",
      "cmbls__Additional_Fees__c",
      "cmbls__Allow_Incremental_Debit__c",
      "cmbls__Allow_Multi_Schedule__c",
      "cmbls__Allow_Payments_greater_than_Invoice__c",
      "cmbls__Amortization_Term__c",
      "cmbls__Amount_Funded_By_Outside_Lender__c",
      "cmbls__Amount_Paid_Interest__c",
      "cmbls__Amount_Paid_Principal__c",
      "cmbls__Amount_applied_to_credit__c",
      "cmbls__Amount_applied_to_credit_in_advance_del__c",
      "cmbls__Amount_applied_to_debit__c",
      "cmbls__Amount_applied_to_debit_in_advance__c",
      "cmbls__Anticipated_Balance__c",
      "cmbls__Anticipated_Daily_Pmt_Amount__c",
      "cmbls__Balance__c",
      "cmbls__Business_Days_Since_Funded__c",
      "cmbls__Calculate_Reserve_Summary_Fields__c",
      "cmbls__Calendar_Days_Since_Funded__c",
      "cmbls__Cash_Collateral_Balance__c",
      "cmbls__Combine_Past_Due_Line_Items__c",
      "cmbls__Consecutive_Error_Codes__c",
      "cmbls__Consecutive_Errors__c",
      "cmbls__Created_From_UI__c",
      "cmbls__Current_Interest_Rate__c",
      "cmbls__Current_Loan_Balance__c",
      "cmbls__Date_Renewed__c",
      "cmbls__Date_completed__c",
      "cmbls__Day_Payment_is_Applied__c",
      "cmbls__Days_Past_Due__c",
      "cmbls__Days_in_Advance_to_Create_Invoice__c",
      "cmbls__Days_since_Funded__c",
      "cmbls__Default_Interest_Rate__c",
      "cmbls__Default_Interest__c",
      "cmbls__Deferred_Fees_Balance__c",
      "cmbls__Deferred_Fees_Credited__c",
      "cmbls__Deferred_Fees_Paid__c",
      "cmbls__Disable_First_Payment_Amount_Adjustment__c",
      "cmbls__Disable_Payment_Allocation__c",
      "cmbls__Disable_Reserve_Collection_After_Date__c",
      "cmbls__Disable_Reserve_Collection_After__c",
      "cmbls__Disable_Reserve_Number_of_Remaining_PMT__c",
      "cmbls__Disbursed_Principal_Balance__c",
      "cmbls__Draw_Reserve_Balance__c",
      "cmbls__Enable_Amortization_Schedule__c",
      "cmbls__Enable_Estimated_Accruals__c",
      "cmbls__Enable_Interest_Accrual__c",
      "cmbls__Enable_Invoicing__c",
      "cmbls__Enable_Reserve_Collection__c",
      "cmbls__Enable_Rule_of_78s__c",
      "cmbls__Escrow_Reserve_Balance__c",
      "cmbls__Estimated_Balance__c",
      "cmbls__Estimated_Days_Until_Payoff__c",
      "cmbls__Estimated_Duration_Business_Days__c",
      "cmbls__Estimated_Duration_Calendar_Days__c",
      "cmbls__Estimated_Monthly_Factor__c",
      "cmbls__Estimated_Monthly_Pmt_Amount__c",
      "cmbls__Estimated_Paid_Percentage__c",
      "cmbls__Estimated_Payments_Remaining__c",
      "cmbls__Estimated_Payoff_Date__c",
      "cmbls__Expected_Days_Until_Payoff__c",
      "cmbls__Expected_Duration_Business_Days__c",
      "cmbls__Expected_Duration_Calendar_Days__c",
      "cmbls__Expected_Monthly_Factor__c",
      "cmbls__Expected_Monthly_Pmt_Amount__c",
      "cmbls__Expected_Paid_Percentage__c",
      "cmbls__Expected_Payments_Remaining__c",
      "cmbls__Expected_Payoff_Date__c",
      "cmbls__Expected_to_Collect_Last_30_Days__c",
      "cmbls__Expected_to_Collect_Last_7_Days__c",
      "cmbls__Expected_to_Collect__c",
      "cmbls__External_ID_Type__c",
      "cmbls__External_ID__c",
      "cmbls__Factor_Rate__c",
      "cmbls__Fee_Balance__c",
      "cmbls__Fee_Group__c",
      "cmbls__First_Hit_Date__c",
      "cmbls__First_Payment_Date__c",
      "cmbls__First_Payment__c",
      "cmbls__First_Settled_Date__c",
      "cmbls__Fixed_Amount_of_Reserve_to_Collect__c",
      "cmbls__Funded_Date__c",
      "cmbls__Funding_Amount__c",
      "cmbls__Holdback__c",
      "cmbls__INV_Principal_from_Amortization_Schedule__c",
      "cmbls__Initial_Payment_Amount__c",
      "cmbls__Interest_Accrual_Frequency__c",
      "cmbls__Interest_Accrual_Method__c",
      "cmbls__Interest_Amt__c",
      "cmbls__Interest_Balance_Amount__c",
      "cmbls__Interest_Creation_Method__c",
      "cmbls__Interest_Paid_To_Date__c",
      "cmbls__Interest_Percentage__c",
      "cmbls__Interest_Reserve_Balance__c",
      "cmbls__Interest_Structure__c",
      "cmbls__Interest__c",
      "cmbls__Intial_Repayment_Amount__c",
      "cmbls__Invoice_Date__c",
      "cmbls__Is_Hybrid__c",
      "cmbls__Is_Interest_Based_Loan__c",
      "cmbls__Is_Variable_Rate__c",
      "cmbls__Last_Batch_Date__c",
      "cmbls__Last_Running_Balance_Execution__c",
      "cmbls__Last_Settlement_Date__c",
      "cmbls__Lender_Reimbursement_Balance__c",
      "cmbls__Lender_Reimbursement_Credited__c",
      "cmbls__Lender_Reimbursement_Paid__c",
      "cmbls__Loan_Amount__c",
      "cmbls__Loan_Start_Date__c",
      "cmbls__Loan_Template__c",
      "cmbls__Management_Fee_to_Outside_Lender__c",
      "cmbls__Management_Fee_to_Outside_Lender_on__c",
      "cmbls__Markup__c",
      "cmbls__Maturity_Date__c",
      "cmbls__Memo__c",
      "cmbls__Merchant_ID__c",
      "cmbls__Mgmt_Fees_Paid_to_Outside_Lender2__c",
      "cmbls__Monthly_Factor_Percentage__c",
      "cmbls__Monthly_Reserve_Payment__c",
      "cmbls__Monthly_Withdrawal_Date__c",
      "cmbls__Months_Since_Funded__c",
      "cmbls__Months_to_Collect_Reserve__c",
      "cmbls__Net_Funding__c",
      "cmbls__Next_Hit_Date__c",
      "cmbls__Next_Payment_Due_Date__c",
      "cmbls__Number_of_Days_Before_First_Payment__c",
      "cmbls__Number_of_Payments__c",
      "cmbls__Number_of_Payments_for_Reserve__c",
      "cmbls__Number_of_Properties__c",
      "cmbls__Open_Balance__c",
      "cmbls__Opportunity_DO_NOT_PACKAGE__c",
      "cmbls__Original_Interest_Rate__c",
      "cmbls__Original_Maturity_Date__c",
      "cmbls__Original_Payoff_Date__c",
      "cmbls__Original_Repayment__c",
      "cmbls__Origination_Fee__c",
      "cmbls__Outside_Servicing_Lender__c",
      "cmbls__Paid_Amt__c",
      "cmbls__Paid_Through_Date__c",
      "cmbls__Paid__c",
      "cmbls__Participation_Amount_with_Outside_Lender__c",
      "cmbls__Participation_with_Outside_Lender2__c",
      "cmbls__Payback_Amount_for_Outside_Lender__c",
      "cmbls__Payment_Amount__c",
      "cmbls__Payment_Due_Date__c",
      "cmbls__Payment_Frequency__c",
      "cmbls__Payment_Method__c",
      "cmbls__Payment_Waterfall__c",
      "cmbls__Payments_Updated__c",
      "cmbls__Payoff_Balance__c",
      "cmbls__Payoff_Group__c",
      "cmbls__Payoff_Repayment__c",
      "cmbls__Payoff__c",
      "cmbls__Pending_Balance__c",
      "cmbls__Performance_Group__c",
      "cmbls__Performance__c",
      "cmbls__Posted_to_Accounting__c",
      "cmbls__Potential_Renewal_Amt__c",
      "cmbls__Principal_Amt__c",
      "cmbls__Principal_Balance_Amount__c",
      "cmbls__Principal__c",
      "cmbls__Processor_Integration__c",
      "cmbls__Processor_Name__c",
      "cmbls__Processor__c",
      "cmbls__Reallocate_Reserve_Paid_To__c",
      "cmbls__Reallocate_Reserve_Paid__c",
      "cmbls__Renewal_Payoff_Amount__c",
      "cmbls__Renewal_Reminder__c",
      "cmbls__Requested_Payoff_Date__c",
      "cmbls__Reserve_Amount_to_Collect_Method__c",
      "cmbls__Reserve_Amount_to_be_Collected__c",
      "cmbls__Reserve_Balance_Due__c",
      "cmbls__Reserve_Balance__c",
      "cmbls__Reserve_Paid__c",
      "cmbls__Reserve_Payment_Due__c",
      "cmbls__Reserve_Requested__c",
      "cmbls__Signed_ACH_Form__c",
      "cmbls__Starting_Draw_Reserve_Balance__c",
      "cmbls__Status__c",
      "cmbls__Sum_Payment_Balance__c",
      "cmbls__Temp_Days_Since_Funded__c",
      "cmbls__Term_Days_Default__c",
      "cmbls__Term_Days__c",
      "cmbls__Term_Months_Input__c",
      "cmbls__Term_Months__c",
      "cmbls__Term_Weeks__c",
      "cmbls__Total_Credits_to_Draw_Reserve__c",
      "cmbls__Total_Debit_Draws__c",
      "cmbls__Total_Debits_to_Draw_Reserve__c",
      "cmbls__Total_Draw_Amount__c",
      "cmbls__Total_Draws_Credited__c",
      "cmbls__Total_Mgmt_Fees_to_be_Paid_to_Outside__c",
      "cmbls__Total_Outstanding_Amount__c",
      "cmbls__Total_Reserve_Deducted__c",
      "cmbls__Total_Reserve_Held__c",
      "cmbls__Total_Write_Off__c",
      "cmbls__Type_of_Account__c",
      "cmbls__Uncollected_Balance__c",
      "cmbls__Upfront_Fee__c",
      "cmbls__Variance_Amount_Balance__c",
      "cmbls__Voided_Check_Received__c",
      "cmbls__Weeks_Since_Funded__c",
      "cmbls__Workflow_Execution__c",
      "cmbls__Write_Off_Date__c",
      "cmbls__Write_Off_Notes__c",
      "cmbls__of_Expected__c",
      "cmbls__Amount_applied_to_credit_fees_applied__c",
      "cmbls__Amount_applied_to_credit_settled__c",
      "cmbls__Amount_applied_to_debit_fees_applied__c",
      "cmbls__Amount_applied_to_debit_settled__c",
      "cmbls__Collections_on_Write_Off__c",
      "cmbls__Count_of_Transactions__c",
      "cmbls__Fees_Post_Write_Off__c",
      "cmbls__Interest_Credited__c",
      "cmbls__Interest_Paid__c",
      "cmbls__Last_Payment_Number__c",
      "cmbls__Pending_Amount__c",
      "cmbls__Principal_Credited__c",
      "cmbls__Principal_Paid__c",
      "cmbls__Total_Amount_Settled__c",
      "cmbls__Total_Collected_New__c",
      "cmbls__Total_Credits_Settled__c",
      "cmbls__Total_Debits_Scheduled__c",
      "cmbls__Total_Deferred_Interest_Write_Off__c",
      "cmbls__Total_Fees_Added__c",
      "cmbls__Total_Fees__c",
      "cmbls__Write_Off_Fees__c",
      "cmbls__Write_Off__c",
      "cmbls__Auto_Settle_Payments_On__c",
      "cmbls__Disable_Updates_to_Recurring_Payment_Cmp__c",
      "cmbls__Enable_Custom_Amortization_Schedule__c",
      "cmbls__Enable_Interest_Statement__c",
      "cmbls__Enable_Metro_2_Reporting__c",
      "cmbls__Enable_SBA_Reporting__c",
      "cmbls__Last_Metro2_Loan_Summary__c",
      "cmbls__Metro2_Account_Status__c",
      "cmbls__Next_Invoice_Date__c",
      "cmbls__Primary_Fund__c",
      "cmbls__Reamortize_Schedule_Upon_Draw__c",
      "MID__c",
      "Opportunity__c",
      "Refund_Amount__c",
      "cmbls__Enable_AS_Fixed_Payback_Loan__c",
      "cmbls__Enable_Amortization_of_Expenses__c",
      "cmbls__Expense_Amortization_Start_Date__c",
      "cmbls__Invoice_Interest_in_Advance__c",
      "cmbls__New_Servicer__c",
      "cmbls__Payments_Only_on_Weekdays__c",
      "cmbls__Purchaser__c",
      "cmbls__Roll_Forward_Date__c",
      "cmbls__Roll_Up_Summary__c",
      "cmbls__Sale_Date__c",
      "Allowance_for_Bad_Debt__c",
      "Amortization_FRPSA_Processing_Fee_GL_Num__c",
      "FRPSA_Fee_Income_GL_Num__c",
      "FRPSA_Processing_Fee_GL_Num__c",
      "FRPSA_Processing_Fee_Revenue_GL_Num__c",
      "Funding_Amort_FRPSA_Proc_Fee_Desc__c",
      "Funding_Disbursement_Desc__c",
      "Funding_Disbursement_GL_Number__c",
      "Funding_FRPSA_Processing_Fee_Rec_Desc__c",
      "Funding_FRPSA_Receivable_Desc__c",
      "Processing_Fee__c",
      "Receivable_GL_Number__c",
      "Collected_Origination_Fee__c",
      "Discount_Early_Repayment__c",
      "Collected_Installment_Payments__c",
      "Open_Installment_Balance__c",
      "FC_Payoff__c",
      "FC_Payoff_Valid_Until__c",
      "cmbls__Amortization_Schedule_Creation_Date__c",
      "cmbls__Compute_Method__c",
      "cmbls__Enable_Month_End_Interest_Accrual__c",
      "Accounting_Review_Result__c",
      "Borrower_Refunded_Amount__c",
      "Gross_Installment_Revenue__c",
      "cmbsa__Amount_Available_for_Syndication__c",
      "cmbsa__Close_Syndication__c",
      "cmbsa__Comp_Percent__c",
      "cmbsa__Comp__c",
      "cmbsa__Date_Syndication_Closed__c",
      "cmbsa__Email_to_Syndicators__c",
      "cmbsa__Force_com_Site_URL__c",
      "cmbsa__Lenders_Funding__c",
      "cmbsa__Management_Fee__c",
      "cmbsa__Management_Fee_of__c",
      "cmbsa__Number_of_Remittances__c",
      "cmbsa__Override_Mgmt_Fees__c",
      "cmbsa__Reserved_by_Syndicators__c",
      "cmbsa__Syndicator_Fees_to_Servicing_Bank__c",
      "cmbsa__Syndicators_Funding_Amount__c",
      "cmbsa__Syndicators_Funding__c",
      "cmbsa__Syndicators_Payback_Amount__c",
      "cmbsa__Term_Months__c",
      "cmbsa__Total_Amount_Paid_Out_to_Syndicator__c",
      "cmbsa__Mgmt_Fee_Collected_from_Syndicators__c",
      "cmbsa__Comp_of_Funded__c",
      "cmbsa__Currently_Available_for_Syndication__c",
      "cmbsa__Lender_s_Funded_Amount__c",
      "cmbsa__Lender_s_Payback_Amount__c",
      "cmbsa__Lender_s_Total_Payback_Amount__c",
      "cmbsa__Participation_still_available__c",
      "cmbsa__Syndicators_Net_Payback_Amount__c",
      "cmbsa__Total_Amount_Paid_to_Lender__c",
      "Refinanced_Collected_Interest__c",
      "Refinanced_Collected_Principal__c",
      "Refinanced_Renewed_Interest__c",
      "Refinanced_Renewed_Principal__c",
      "Collected_Interest__c",
      "Collected_Principal__c",
      "Extension_Interest__c",
      "Extension_Principal__c",
      "Adjusted_Funded_Amount__c",
      "Adjusted_Repayment_Amount__c",
      "Refinanced_Add_on__c",
      "Customer_Service_Issue__c",
      "Customer_Service_Notes__c",
      "Modified_Payment_Structure__c",
      "Count_of_Settled_Payments__c",
      "Count_of_Remaining_Payments__c",
      "Initial_Installment_Amount__c",
      "Count_of_Failed_Payments__c",
      "Last_Bounce_Date__c",
      "Last_Payment_Received_Date__c",
      "Failure_Rate__c",
      "Pacing_Per__c",
      "Past_Due__c",
      "Fee_Only__c",
      "Count_of_Expected_Payments__c",
      "Extension_Total__c",
      "Adjusted_Rate_Factor__c",
      "Account_State_of_Business_Registration__c",
      "Reconciliation_Status__c",
      "Impact_Per__c",
      "Test_Record__c",
      "Partner_Commissionable_Amount__c",
      "Collections_Status__c",
      "Installment_Amount_Collected__c",
      "Refinanced_Total__c",
      "Refinanced_Collected_Total__c",
      "Ancillary_Fees_Added__c",
      "Num_Days_Past_Due__c",
      "cmbls__Additional_Net_Funding_Transactions__c",
      "cmbls__Amortization_Schedule_Creation_Datetime__c",
      "cmbls__Default_Interest_Allowance__c",
      "cmbls__Enable_Advances_to_Cover_Interest_Charge__c",
      "cmbls__Enable_Custom_Reserve__c",
      "cmbls__Enable_Participation_Compatibility__c",
      "cmbls__Interest_Rate_Index__c",
      "cmbls__Invoice_Minimum_Payment__c",
      "cmbls__Minimum_Payment__c",
      "cmbls__NACHA_Individual_Name__c",
      "cmbls__Origination_Fee_Not_Netted__c",
      "cmbls__Revolving_Line_of_Credit__c"
    FROM
      "SFDC"."STAGE"."CMBLS__REPAYMENT__C"
  ),
  "PaymentAggregation" AS (
    SELECT
      "cmbls__Repayment__c" AS "cmbls__Repayment__c",
      SUM("Failed Payment") AS "SUM_Failed Payment",
      MIN("Failed Payment Date") AS "MIN_Failed Payment Date",
      MAX("Failed Payment Date") AS "MAX_Failed Payment Date"
    FROM
      "MANAGE COLUMNS"
    GROUP BY
      "cmbls__Repayment__c"
  ),
  "OppApp_w_Account" AS (
    SELECT
      LHS.*,
      RHS."Id" AS "Id_RHS",
      RHS."Name" AS "Name_RHS1",
      RHS."Type" AS "Type_RHS",
      RHS."RecordTypeId" AS "RecordTypeId_RHS",
      RHS."ParentId",
      RHS."BillingAddress",
      RHS."ShippingAddress",
      RHS."Phone",
      RHS."Website",
      RHS."Industry",
      RHS."AnnualRevenue",
      RHS."NumberOfEmployees",
      RHS."Description" AS "Description_RHS",
      RHS."OwnerId" AS "OwnerId_RHS",
      RHS."CreatedDate" AS "CreatedDate_RHS",
      RHS."CreatedById" AS "CreatedById_RHS",
      RHS."LastActivityDate" AS "LastActivityDate_RHS",
      RHS."LastViewedDate" AS "LastViewedDate_RHS",
      RHS."IsPartner",
      RHS."ChannelProgramName",
      RHS."ChannelProgramLevelName",
      RHS."AccountSource",
      RHS."Industry_Vertical__c",
      RHS."Business_Entity_Type__c",
      RHS."State_of_Business_Registration__c",
      RHS."Date_Established__c",
      RHS."cmbls__Email_Address__c",
      RHS."DBA__c",
      RHS."Customer_Id__c",
      RHS."Seed_to_Sale_Software__c",
      RHS."Federal_Tax_Id__c",
      RHS."McaApp__Balance__c",
      RHS."McaApp__Bank_Acct_Nums__c",
      RHS."McaApp__Business_Name__c",
      RHS."McaApp__Business_Phone__c",
      RHS."McaApp__DBA_Name__c",
      RHS."McaApp__Date_Business_Established__c",
      RHS."McaApp__Email__c" AS "McaApp__Email__c_RHS",
      RHS."McaApp__Federal_Tax_ID_No__c",
      RHS."McaApp__Is_Seasonal__c",
      RHS."McaApp__Lease_start_date__c",
      RHS."McaApp__Legal_Name__c",
      RHS."McaApp__Length_of_Ownership__c",
      RHS."McaApp__MIDs__c",
      RHS."McaApp__Main_Contact__c",
      RHS."McaApp__Monthly_Bank_Deposit_Avg_All__c",
      RHS."McaApp__NumberofLocations__c",
      RHS."McaApp__Owner_1_City__c",
      RHS."McaApp__Payback_Funded__c",
      RHS."McaApp__Property_Type__c",
      RHS."McaApp__State_Of_Incorporation__c",
      RHS."McaApp__Total_Comissions_Amount__c",
      RHS."McaApp__Total_Funded_Amount__c",
      RHS."McaApp__Type_of_Entity__c",
      RHS."McaApp__Years_in_Business__c",
      RHS."McaApp__Count_Of_Opportunities__c",
      RHS."cmbla__ISO_Checklist__c",
      RHS."cmbla__SLAExpirationDate__c",
      RHS."New_Funding_Fee_Example__c",
      RHS."New_Funding_Fee_Percent__c",
      RHS."Renewal_Compensation_Eligibility__c",
      RHS."Renewal_Funding_Fee_Example__c",
      RHS."Renewal_Funding_Fee_Percent__c",
      RHS."Partner_Web_External_Id__c",
      RHS."Strategic_Partner__c" AS "Strategic_Partner__c_RHS",
      RHS."All_Time_Funded_Deal_Count__c",
      RHS."Total_Repaid_Deals__c",
      RHS."Years_In_Business__c",
      RHS."County__c",
      RHS."Initial_Application_In_Date__c",
      RHS."Referral_Contact__c",
      RHS."Approval_Available_Amount__c" AS "Approval_Available_Amount__c_RHS",
      RHS."Approval_Amount__c" AS "Approval_Amount__c_RHS",
      RHS."Approval_Depleted_Amount__c" AS "Approval_Depleted_Amount__c_RHS",
      RHS."Approval_Expiration_Date__c" AS "Approval_Expiration_Date__c_RHS1",
      RHS."Num_Opportunities__c",
      RHS."DOZISF__ZoomInfo_Last_Updated__c",
      RHS."NAICS_Code__c",
      RHS."cmbls__Billing_City_And_State__c",
      RHS."Master_Approval_Amount__c" AS "Master_Approval_Amount__c_RHS",
      RHS."Master_Approval_Expiration__c" AS "Master_Approval_Expiration__c_RHS",
      RHS."Master_Approval_Status__c",
      RHS."Master_Current_Utilization_Amount__c",
      RHS."Master_Approval_Amount_Available__c",
      RHS."All_Time_Funded_Amount__c",
      RHS."Initial_Funded_Amount__c",
      RHS."Lead_Initial_Create_Date__c" AS "Lead_Initial_Create_Date__c_RHS",
      RHS."Initial_Lead_Source__c" AS "Initial_Lead_Source__c_RHS",
      RHS."Initial_Campaign__c",
      RHS."List_Source__c",
      RHS."EID__c",
      RHS."Strategic_Partner_Status__c",
      RHS."cmbsa__Syndicator__c",
      RHS."Commission_Roll_Up__c",
      RHS."Licensed_State__c",
      RHS."Prospect_Status__c",
      RHS."Test_Record__c" AS "Test_Record__c_RHS1",
      RHS."n2de__Distribution_count__c" AS "n2de__Distribution_count__c_RHS",
      RHS."n2de__Distribution_engine_details__c" AS "n2de__Distribution_engine_details__c_RHS",
      RHS."n2de__Is_distributed__c" AS "n2de__Is_distributed__c_RHS",
      RHS."n2de__Is_reassigned__c" AS "n2de__Is_reassigned__c_RHS",
      RHS."n2de__Last_distributed__c" AS "n2de__Last_distributed__c_RHS",
      RHS."n2de__Last_reassigned__c" AS "n2de__Last_reassigned__c_RHS",
      RHS."n2de__Time_to_action_mins__c" AS "n2de__Time_to_action_mins__c_RHS",
      RHS."Payment_Preference__c",
      RHS."BillingCity",
      RHS."BillingPostalCode",
      RHS."BillingState",
      RHS."BillingStreet"
    FROM
      "Opps_w_TeamMembers" LHS
      LEFT OUTER JOIN "Accounts" RHS ON LHS."AccountId" = RHS."Id"
  ),
  "Repayments_w_Payments" AS (
    SELECT
      LHS.*,
      RHS."cmbls__Repayment__c",
      RHS."SUM_Failed Payment",
      RHS."MIN_Failed Payment Date",
      RHS."MAX_Failed Payment Date"
    FROM
      "Repaymnet" LHS
      LEFT OUTER JOIN "PaymentAggregation" RHS ON LHS."Id" = RHS."cmbls__Repayment__c"
  ),
  "CreditReport by OppID" AS (
    SELECT
      *
    FROM
      (
        SELECT
          "OpportunityId",
          "Credit_Report__c",
          ROW_NUMBER() OVER (
            PARTITION BY
              "OpportunityId"
            ORDER BY
              "OpportunityId",
              "Credit_Report__c" desc
          ) RNO
        from
          SFDC.STAGE.OPPORTUNITYCONTACTROLE
        WHERE
          "Credit_Report__c" IS NOT NULL
      )
    WHERE
      RNO = 1
  ),
  "CreditCheckerFields" AS (
    SELECT
      "Id" AS "Id_CreditReport",
      "creditchecker__Average_Score__c",
      "creditchecker__Adverse_Alert__c",
      "creditchecker__Total_Score_Model__c"
    FROM
      "SFDC"."STAGE"."CREDITCHECKER__CREDIT_REPORT__C"
  ),
  "Opps_w_Repayment" AS (
    SELECT
      LHS.*,
      RHS."Id" AS "Id_RHS1",
      RHS."Name" AS "Name_RHS2",
      RHS."RecordTypeId" AS "RecordTypeId_RHS1",
      RHS."CreatedDate" AS "CreatedDate_RHS1",
      RHS."cmbls__Payee_Account__c",
      RHS."cmbls__Accrued_Interest__c",
      RHS."cmbls__Additional_Fees__c",
      RHS."cmbls__Allow_Incremental_Debit__c",
      RHS."cmbls__Allow_Multi_Schedule__c",
      RHS."cmbls__Allow_Payments_greater_than_Invoice__c",
      RHS."cmbls__Amortization_Term__c",
      RHS."cmbls__Amount_Funded_By_Outside_Lender__c",
      RHS."cmbls__Amount_Paid_Interest__c",
      RHS."cmbls__Amount_Paid_Principal__c",
      RHS."cmbls__Amount_applied_to_credit__c",
      RHS."cmbls__Amount_applied_to_credit_in_advance_del__c",
      RHS."cmbls__Amount_applied_to_debit__c",
      RHS."cmbls__Amount_applied_to_debit_in_advance__c",
      RHS."cmbls__Anticipated_Balance__c",
      RHS."cmbls__Anticipated_Daily_Pmt_Amount__c",
      RHS."cmbls__Balance__c",
      RHS."cmbls__Business_Days_Since_Funded__c",
      RHS."cmbls__Calculate_Reserve_Summary_Fields__c",
      RHS."cmbls__Calendar_Days_Since_Funded__c",
      RHS."cmbls__Cash_Collateral_Balance__c",
      RHS."cmbls__Combine_Past_Due_Line_Items__c",
      RHS."cmbls__Consecutive_Error_Codes__c",
      RHS."cmbls__Consecutive_Errors__c",
      RHS."cmbls__Created_From_UI__c",
      RHS."cmbls__Current_Interest_Rate__c",
      RHS."cmbls__Current_Loan_Balance__c",
      RHS."cmbls__Date_Renewed__c",
      RHS."cmbls__Date_completed__c",
      RHS."cmbls__Day_Payment_is_Applied__c",
      RHS."cmbls__Days_Past_Due__c",
      RHS."cmbls__Days_in_Advance_to_Create_Invoice__c",
      RHS."cmbls__Days_since_Funded__c",
      RHS."cmbls__Default_Interest_Rate__c",
      RHS."cmbls__Default_Interest__c",
      RHS."cmbls__Deferred_Fees_Balance__c",
      RHS."cmbls__Deferred_Fees_Credited__c",
      RHS."cmbls__Deferred_Fees_Paid__c",
      RHS."cmbls__Disable_First_Payment_Amount_Adjustment__c",
      RHS."cmbls__Disable_Payment_Allocation__c",
      RHS."cmbls__Disable_Reserve_Collection_After_Date__c",
      RHS."cmbls__Disable_Reserve_Collection_After__c",
      RHS."cmbls__Disable_Reserve_Number_of_Remaining_PMT__c",
      RHS."cmbls__Disbursed_Principal_Balance__c",
      RHS."cmbls__Draw_Reserve_Balance__c",
      RHS."cmbls__Enable_Amortization_Schedule__c",
      RHS."cmbls__Enable_Estimated_Accruals__c",
      RHS."cmbls__Enable_Interest_Accrual__c",
      RHS."cmbls__Enable_Invoicing__c",
      RHS."cmbls__Enable_Reserve_Collection__c",
      RHS."cmbls__Enable_Rule_of_78s__c",
      RHS."cmbls__Escrow_Reserve_Balance__c",
      RHS."cmbls__Estimated_Balance__c",
      RHS."cmbls__Estimated_Days_Until_Payoff__c",
      RHS."cmbls__Estimated_Duration_Business_Days__c",
      RHS."cmbls__Estimated_Duration_Calendar_Days__c",
      RHS."cmbls__Estimated_Monthly_Factor__c",
      RHS."cmbls__Estimated_Monthly_Pmt_Amount__c",
      RHS."cmbls__Estimated_Paid_Percentage__c",
      RHS."cmbls__Estimated_Payments_Remaining__c",
      RHS."cmbls__Estimated_Payoff_Date__c",
      RHS."cmbls__Expected_Days_Until_Payoff__c",
      RHS."cmbls__Expected_Duration_Business_Days__c",
      RHS."cmbls__Expected_Duration_Calendar_Days__c",
      RHS."cmbls__Expected_Monthly_Factor__c",
      RHS."cmbls__Expected_Monthly_Pmt_Amount__c",
      RHS."cmbls__Expected_Paid_Percentage__c",
      RHS."cmbls__Expected_Payments_Remaining__c",
      RHS."cmbls__Expected_Payoff_Date__c",
      RHS."cmbls__Expected_to_Collect_Last_30_Days__c",
      RHS."cmbls__Expected_to_Collect_Last_7_Days__c",
      RHS."cmbls__Expected_to_Collect__c",
      RHS."cmbls__External_ID_Type__c",
      RHS."cmbls__External_ID__c",
      RHS."cmbls__Factor_Rate__c",
      RHS."cmbls__Fee_Balance__c",
      RHS."cmbls__Fee_Group__c",
      RHS."cmbls__First_Hit_Date__c",
      RHS."cmbls__First_Payment_Date__c",
      RHS."cmbls__First_Payment__c",
      RHS."cmbls__First_Settled_Date__c",
      RHS."cmbls__Fixed_Amount_of_Reserve_to_Collect__c",
      RHS."cmbls__Funded_Date__c",
      RHS."cmbls__Funding_Amount__c",
      RHS."cmbls__Holdback__c",
      RHS."cmbls__INV_Principal_from_Amortization_Schedule__c",
      RHS."cmbls__Initial_Payment_Amount__c",
      RHS."cmbls__Interest_Accrual_Frequency__c",
      RHS."cmbls__Interest_Accrual_Method__c",
      RHS."cmbls__Interest_Amt__c",
      RHS."cmbls__Interest_Balance_Amount__c",
      RHS."cmbls__Interest_Creation_Method__c",
      RHS."cmbls__Interest_Paid_To_Date__c",
      RHS."cmbls__Interest_Percentage__c",
      RHS."cmbls__Interest_Reserve_Balance__c",
      RHS."cmbls__Interest_Structure__c",
      RHS."cmbls__Interest__c",
      RHS."cmbls__Intial_Repayment_Amount__c",
      RHS."cmbls__Invoice_Date__c",
      RHS."cmbls__Is_Hybrid__c",
      RHS."cmbls__Is_Interest_Based_Loan__c",
      RHS."cmbls__Is_Variable_Rate__c",
      RHS."cmbls__Last_Batch_Date__c",
      RHS."cmbls__Last_Running_Balance_Execution__c",
      RHS."cmbls__Last_Settlement_Date__c",
      RHS."cmbls__Lender_Reimbursement_Balance__c",
      RHS."cmbls__Lender_Reimbursement_Credited__c",
      RHS."cmbls__Lender_Reimbursement_Paid__c",
      RHS."cmbls__Loan_Amount__c",
      RHS."cmbls__Loan_Start_Date__c",
      RHS."cmbls__Loan_Template__c",
      RHS."cmbls__Management_Fee_to_Outside_Lender__c",
      RHS."cmbls__Management_Fee_to_Outside_Lender_on__c",
      RHS."cmbls__Markup__c",
      RHS."cmbls__Maturity_Date__c",
      RHS."cmbls__Memo__c",
      RHS."cmbls__Merchant_ID__c",
      RHS."cmbls__Mgmt_Fees_Paid_to_Outside_Lender2__c",
      RHS."cmbls__Monthly_Factor_Percentage__c",
      RHS."cmbls__Monthly_Reserve_Payment__c",
      RHS."cmbls__Monthly_Withdrawal_Date__c",
      RHS."cmbls__Months_Since_Funded__c",
      RHS."cmbls__Months_to_Collect_Reserve__c",
      RHS."cmbls__Net_Funding__c",
      RHS."cmbls__Next_Hit_Date__c",
      RHS."cmbls__Next_Payment_Due_Date__c",
      RHS."cmbls__Number_of_Days_Before_First_Payment__c",
      RHS."cmbls__Number_of_Payments__c",
      RHS."cmbls__Number_of_Payments_for_Reserve__c",
      RHS."cmbls__Number_of_Properties__c",
      RHS."cmbls__Open_Balance__c",
      RHS."cmbls__Opportunity_DO_NOT_PACKAGE__c",
      RHS."cmbls__Original_Interest_Rate__c",
      RHS."cmbls__Original_Maturity_Date__c",
      RHS."cmbls__Original_Payoff_Date__c",
      RHS."cmbls__Original_Repayment__c",
      RHS."cmbls__Origination_Fee__c",
      RHS."cmbls__Outside_Servicing_Lender__c",
      RHS."cmbls__Paid_Amt__c",
      RHS."cmbls__Paid_Through_Date__c",
      RHS."cmbls__Paid__c",
      RHS."cmbls__Participation_Amount_with_Outside_Lender__c",
      RHS."cmbls__Participation_with_Outside_Lender2__c",
      RHS."cmbls__Payback_Amount_for_Outside_Lender__c",
      RHS."cmbls__Payment_Amount__c",
      RHS."cmbls__Payment_Due_Date__c",
      RHS."cmbls__Payment_Frequency__c",
      RHS."cmbls__Payment_Method__c",
      RHS."cmbls__Payment_Waterfall__c",
      RHS."cmbls__Payments_Updated__c",
      RHS."cmbls__Payoff_Balance__c",
      RHS."cmbls__Payoff_Group__c",
      RHS."cmbls__Payoff_Repayment__c",
      RHS."cmbls__Payoff__c",
      RHS."cmbls__Pending_Balance__c",
      RHS."cmbls__Performance_Group__c",
      RHS."cmbls__Performance__c",
      RHS."cmbls__Posted_to_Accounting__c",
      RHS."cmbls__Potential_Renewal_Amt__c",
      RHS."cmbls__Principal_Amt__c",
      RHS."cmbls__Principal_Balance_Amount__c",
      RHS."cmbls__Principal__c",
      RHS."cmbls__Processor_Integration__c",
      RHS."cmbls__Processor_Name__c",
      RHS."cmbls__Processor__c",
      RHS."cmbls__Reallocate_Reserve_Paid_To__c",
      RHS."cmbls__Reallocate_Reserve_Paid__c",
      RHS."cmbls__Renewal_Payoff_Amount__c",
      RHS."cmbls__Renewal_Reminder__c",
      RHS."cmbls__Requested_Payoff_Date__c",
      RHS."cmbls__Reserve_Amount_to_Collect_Method__c",
      RHS."cmbls__Reserve_Amount_to_be_Collected__c",
      RHS."cmbls__Reserve_Balance_Due__c",
      RHS."cmbls__Reserve_Balance__c",
      RHS."cmbls__Reserve_Paid__c",
      RHS."cmbls__Reserve_Payment_Due__c",
      RHS."cmbls__Reserve_Requested__c",
      RHS."cmbls__Signed_ACH_Form__c",
      RHS."cmbls__Starting_Draw_Reserve_Balance__c",
      RHS."cmbls__Status__c",
      RHS."cmbls__Sum_Payment_Balance__c",
      RHS."cmbls__Temp_Days_Since_Funded__c",
      RHS."cmbls__Term_Days_Default__c",
      RHS."cmbls__Term_Days__c",
      RHS."cmbls__Term_Months_Input__c",
      RHS."cmbls__Term_Months__c",
      RHS."cmbls__Term_Weeks__c",
      RHS."cmbls__Total_Credits_to_Draw_Reserve__c",
      RHS."cmbls__Total_Debit_Draws__c",
      RHS."cmbls__Total_Debits_to_Draw_Reserve__c",
      RHS."cmbls__Total_Draw_Amount__c",
      RHS."cmbls__Total_Draws_Credited__c",
      RHS."cmbls__Total_Mgmt_Fees_to_be_Paid_to_Outside__c",
      RHS."cmbls__Total_Outstanding_Amount__c",
      RHS."cmbls__Total_Reserve_Deducted__c",
      RHS."cmbls__Total_Reserve_Held__c",
      RHS."cmbls__Total_Write_Off__c",
      RHS."cmbls__Type_of_Account__c",
      RHS."cmbls__Uncollected_Balance__c",
      RHS."cmbls__Upfront_Fee__c",
      RHS."cmbls__Variance_Amount_Balance__c",
      RHS."cmbls__Voided_Check_Received__c",
      RHS."cmbls__Weeks_Since_Funded__c",
      RHS."cmbls__Workflow_Execution__c",
      RHS."cmbls__Write_Off_Date__c",
      RHS."cmbls__Write_Off_Notes__c",
      RHS."cmbls__of_Expected__c",
      RHS."cmbls__Amount_applied_to_credit_fees_applied__c",
      RHS."cmbls__Amount_applied_to_credit_settled__c",
      RHS."cmbls__Amount_applied_to_debit_fees_applied__c",
      RHS."cmbls__Amount_applied_to_debit_settled__c",
      RHS."cmbls__Collections_on_Write_Off__c",
      RHS."cmbls__Count_of_Transactions__c",
      RHS."cmbls__Fees_Post_Write_Off__c",
      RHS."cmbls__Interest_Credited__c",
      RHS."cmbls__Interest_Paid__c",
      RHS."cmbls__Last_Payment_Number__c",
      RHS."cmbls__Pending_Amount__c",
      RHS."cmbls__Principal_Credited__c",
      RHS."cmbls__Principal_Paid__c",
      RHS."cmbls__Total_Amount_Settled__c",
      RHS."cmbls__Total_Collected_New__c",
      RHS."cmbls__Total_Credits_Settled__c",
      RHS."cmbls__Total_Debits_Scheduled__c",
      RHS."cmbls__Total_Deferred_Interest_Write_Off__c",
      RHS."cmbls__Total_Fees_Added__c",
      RHS."cmbls__Total_Fees__c",
      RHS."cmbls__Write_Off_Fees__c",
      RHS."cmbls__Write_Off__c",
      RHS."cmbls__Auto_Settle_Payments_On__c",
      RHS."cmbls__Disable_Updates_to_Recurring_Payment_Cmp__c",
      RHS."cmbls__Enable_Custom_Amortization_Schedule__c",
      RHS."cmbls__Enable_Interest_Statement__c",
      RHS."cmbls__Enable_Metro_2_Reporting__c",
      RHS."cmbls__Enable_SBA_Reporting__c",
      RHS."cmbls__Last_Metro2_Loan_Summary__c",
      RHS."cmbls__Metro2_Account_Status__c",
      RHS."cmbls__Next_Invoice_Date__c",
      RHS."cmbls__Primary_Fund__c",
      RHS."cmbls__Reamortize_Schedule_Upon_Draw__c",
      RHS."MID__c",
      RHS."Opportunity__c" AS "Opportunity__c_RHS",
      RHS."Refund_Amount__c",
      RHS."cmbls__Enable_AS_Fixed_Payback_Loan__c",
      RHS."cmbls__Enable_Amortization_of_Expenses__c",
      RHS."cmbls__Expense_Amortization_Start_Date__c",
      RHS."cmbls__Invoice_Interest_in_Advance__c",
      RHS."cmbls__New_Servicer__c",
      RHS."cmbls__Payments_Only_on_Weekdays__c",
      RHS."cmbls__Purchaser__c",
      RHS."cmbls__Roll_Forward_Date__c",
      RHS."cmbls__Roll_Up_Summary__c",
      RHS."cmbls__Sale_Date__c",
      RHS."Allowance_for_Bad_Debt__c",
      RHS."Amortization_FRPSA_Processing_Fee_GL_Num__c",
      RHS."FRPSA_Fee_Income_GL_Num__c",
      RHS."FRPSA_Processing_Fee_GL_Num__c",
      RHS."FRPSA_Processing_Fee_Revenue_GL_Num__c",
      RHS."Funding_Amort_FRPSA_Proc_Fee_Desc__c",
      RHS."Funding_Disbursement_Desc__c",
      RHS."Funding_Disbursement_GL_Number__c",
      RHS."Funding_FRPSA_Processing_Fee_Rec_Desc__c",
      RHS."Funding_FRPSA_Receivable_Desc__c",
      RHS."Processing_Fee__c",
      RHS."Receivable_GL_Number__c",
      RHS."Collected_Origination_Fee__c",
      RHS."Discount_Early_Repayment__c",
      RHS."Collected_Installment_Payments__c",
      RHS."Open_Installment_Balance__c",
      RHS."FC_Payoff__c",
      RHS."FC_Payoff_Valid_Until__c",
      RHS."cmbls__Amortization_Schedule_Creation_Date__c",
      RHS."cmbls__Compute_Method__c",
      RHS."cmbls__Enable_Month_End_Interest_Accrual__c",
      RHS."Accounting_Review_Result__c",
      RHS."Borrower_Refunded_Amount__c",
      RHS."Gross_Installment_Revenue__c",
      RHS."cmbsa__Amount_Available_for_Syndication__c",
      RHS."cmbsa__Close_Syndication__c",
      RHS."cmbsa__Comp_Percent__c",
      RHS."cmbsa__Comp__c",
      RHS."cmbsa__Date_Syndication_Closed__c",
      RHS."cmbsa__Email_to_Syndicators__c",
      RHS."cmbsa__Force_com_Site_URL__c",
      RHS."cmbsa__Lenders_Funding__c",
      RHS."cmbsa__Management_Fee__c",
      RHS."cmbsa__Management_Fee_of__c",
      RHS."cmbsa__Number_of_Remittances__c",
      RHS."cmbsa__Override_Mgmt_Fees__c",
      RHS."cmbsa__Reserved_by_Syndicators__c",
      RHS."cmbsa__Syndicator_Fees_to_Servicing_Bank__c",
      RHS."cmbsa__Syndicators_Funding_Amount__c",
      RHS."cmbsa__Syndicators_Funding__c",
      RHS."cmbsa__Syndicators_Payback_Amount__c",
      RHS."cmbsa__Term_Months__c",
      RHS."cmbsa__Total_Amount_Paid_Out_to_Syndicator__c",
      RHS."cmbsa__Mgmt_Fee_Collected_from_Syndicators__c",
      RHS."cmbsa__Comp_of_Funded__c",
      RHS."cmbsa__Currently_Available_for_Syndication__c",
      RHS."cmbsa__Lender_s_Funded_Amount__c",
      RHS."cmbsa__Lender_s_Payback_Amount__c",
      RHS."cmbsa__Lender_s_Total_Payback_Amount__c",
      RHS."cmbsa__Participation_still_available__c",
      RHS."cmbsa__Syndicators_Net_Payback_Amount__c",
      RHS."cmbsa__Total_Amount_Paid_to_Lender__c",
      RHS."Refinanced_Collected_Interest__c",
      RHS."Refinanced_Collected_Principal__c",
      RHS."Refinanced_Renewed_Interest__c",
      RHS."Refinanced_Renewed_Principal__c",
      RHS."Collected_Interest__c",
      RHS."Collected_Principal__c",
      RHS."Extension_Interest__c",
      RHS."Extension_Principal__c",
      RHS."Adjusted_Funded_Amount__c",
      RHS."Adjusted_Repayment_Amount__c",
      RHS."Refinanced_Add_on__c",
      RHS."Customer_Service_Issue__c",
      RHS."Customer_Service_Notes__c",
      RHS."Modified_Payment_Structure__c",
      RHS."Count_of_Settled_Payments__c",
      RHS."Count_of_Remaining_Payments__c",
      RHS."Initial_Installment_Amount__c",
      RHS."Count_of_Failed_Payments__c",
      RHS."Last_Bounce_Date__c",
      RHS."Last_Payment_Received_Date__c",
      RHS."Failure_Rate__c",
      RHS."Pacing_Per__c",
      RHS."Past_Due__c",
      RHS."Fee_Only__c",
      RHS."Count_of_Expected_Payments__c",
      RHS."Extension_Total__c",
      RHS."Adjusted_Rate_Factor__c",
      RHS."Account_State_of_Business_Registration__c",
      RHS."Reconciliation_Status__c",
      RHS."Impact_Per__c",
      RHS."Test_Record__c" AS "Test_Record__c_RHS2",
      RHS."Partner_Commissionable_Amount__c",
      RHS."Collections_Status__c",
      RHS."Installment_Amount_Collected__c" AS "Installment_Amount_Collected__c_RHS",
      RHS."Refinanced_Total__c",
      RHS."Refinanced_Collected_Total__c",
      RHS."Ancillary_Fees_Added__c",
      RHS."Num_Days_Past_Due__c",
      RHS."cmbls__Additional_Net_Funding_Transactions__c",
      RHS."cmbls__Amortization_Schedule_Creation_Datetime__c",
      RHS."cmbls__Default_Interest_Allowance__c",
      RHS."cmbls__Enable_Advances_to_Cover_Interest_Charge__c",
      RHS."cmbls__Enable_Custom_Reserve__c",
      RHS."cmbls__Enable_Participation_Compatibility__c",
      RHS."cmbls__Interest_Rate_Index__c",
      RHS."cmbls__Invoice_Minimum_Payment__c",
      RHS."cmbls__Minimum_Payment__c",
      RHS."cmbls__NACHA_Individual_Name__c",
      RHS."cmbls__Origination_Fee_Not_Netted__c",
      RHS."cmbls__Revolving_Line_of_Credit__c",
      RHS."cmbls__Repayment__c",
      RHS."SUM_Failed Payment",
      RHS."MIN_Failed Payment Date",
      RHS."MAX_Failed Payment Date"
    FROM
      "OppApp_w_Account" LHS
      LEFT OUTER JOIN "Repayments_w_Payments" RHS ON LHS."Id" = RHS."Opportunity__c"
  ),
  "CreditReportFields" AS (
    SELECT
      LHS.*,
      RHS."Id_CreditReport",
      RHS."creditchecker__Average_Score__c",
      RHS."creditchecker__Adverse_Alert__c",
      RHS."creditchecker__Total_Score_Model__c"
    FROM
      "CreditReport by OppID" LHS
      INNER JOIN "CreditCheckerFields" RHS ON LHS."Credit_Report__c" = RHS."Id_CreditReport"
  ),
  "Opps_Repayment_CreditCheck" AS (
    SELECT
      LHS.*,
      RHS."OpportunityId",
      RHS."Credit_Report__c",
      RHS."RNO" AS "RNO_RHS",
      RHS."Id_CreditReport",
      RHS."creditchecker__Average_Score__c" AS "creditchecker__Average_Score__c_RHS",
      RHS."creditchecker__Adverse_Alert__c" AS "creditchecker__Adverse_Alert__c_RHS",
      RHS."creditchecker__Total_Score_Model__c"
    FROM
      "Opps_w_Repayment" LHS
      LEFT OUTER JOIN "CreditReportFields" RHS ON LHS."Id" = RHS."OpportunityId"
  ),
  "HistoricalCreditReport" AS (
    SELECT
      "OpportunityId" AS "OppId_CreditHistory",
      "Credit Score Lookup"
    FROM
      "SFDC"."STAGE"."SNAPSHOT_FICO_H12023"
  ),
  "Opp_w_HistoryicalCredit" AS (
    SELECT
      LHS.*,
      RHS."OppId_CreditHistory",
      RHS."Credit Score Lookup"
    FROM
      "Opps_Repayment_CreditCheck" LHS
      LEFT OUTER JOIN "HistoricalCreditReport" RHS ON LHS."Id" = RHS."OppId_CreditHistory"
  )
select
  "Name" "Opportunity Name",
  "Name_RHS1" "Account Name",
  "DBA__c" "DBA Name",
  "Agreement_Number__c" "Agreemnet Number"
  // KEY DATES
,
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    )
  ) as "Application Date",
  to_date(
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Approval_Date__c")
  ) as "Approval Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Approval_Expiration_Date__c"
    )
  ) as "Approval Expiration Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "McaApp__Date_Contract_Signed__c"
    )
  ) as "Contracts In Date",
  to_date(
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Funded_Date__c")
  ) as "Funded Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "cmbls__Write_Off_Date__c"
    )
  ) as "Write Off Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Contract_In_Date__c"
    )
  ) as "Contract In Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Contract_Out_Date__c"
    )
  ) as "Contract Out Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Due_Diligence_Date__c"
    )
  ) as "Due Diligence Date",
  to_date(
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Processing_Date__c"
    )
  ) as "Processing Date",
  to_date(
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Declined_Date__c")
  ) as "Decline Date",
  CASE
    WHEN "Approval_Date__c" IS NOT NULL THEN CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Approval_Date__c")
    WHEN "Declined_Date__c" IS NOT NULL THEN CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Declined_Date__c")
    ELSE NULL
  END "UW Decision Date"
  //ORIGINATION DIMENSIONS
,
  "Type",
  CASE
    WHEN "RecordTypeId" = '0125f0000002rzeAAA' THEN 'Vendor Financing'
    WHEN "RecordTypeId" = '0125f000000W1MgAAK' THEN 'Vendor Financing (Fee Only)'
    WHEN "RecordTypeId" = '0125f0000002rzfAAA' THEN 'Working Capital'
    WHEN "RecordTypeId" = '0125f000000qtfVAAQ' THEN 'Working Capital (Fee Only)'
    ELSE 'Unknown'
  END "Opportunity Record Type",
  "Industry" "Industry",
  "Industry_Vertical__c" "Industry Vertical",
  "State_of_Business_Registration__c" "State of Business Registration",
  "Business_Entity_Type__c" "Business Entity Type",
  "BillingState" "Billing State",
  "BillingCity" "Billing City",
  "BillingPostalCode" "Billing Postal Code",
  "StageName" as "Opportunity Stage",
  "Strategic_Partner__c" "Strategic PartnerID"
  //ORIGINATION FACTS
,
  IFF(
    "Gross_Annual_Sales__c_RHS" is null,
    "Gross_Annual_Sales__c",
    "Gross_Annual_Sales__c_RHS"
  ) "Gross Annual Sales",
  "Maximum_Approval__c" "Maximum Approval",
  "Years_In_Business__c",
  "Rate_Factor__c" "Rate Factor",
  "Payment_Amount__c" "Paymnet Amount",
  "Payment_Frequency__c" "Paymnet Frequency"
  // FUNDING FACTS
,
  iff(
    "Funded_Date__c" IS NOT NULL,
    "Funded_Amount__c",
    NULL
  ) "Funded Amount",
  iff(
    "Funded_Date__c" IS NOT NULL,
    "cmbls__Interest_Amt__c",
    NULL
  ) "Interest Amount",
  "Term_Months__c" "Term",
  iff(
    "Funded_Date__c" IS NOT NULL,
    "Repayment_Amount__c",
    NULL
  ) "Repayment Amount",
  iff(
    "Funded_Date__c" IS NOT NULL,
    "Extension_Total__c",
    NULL
  ) "Extension Total",
  "Installment_Amount_Collected__c_RHS" "Installment Amount Collected"
  //PERFORMANCE FACTS
,
  "Days_Money_Out__c" "Days Money Out",
  "Discount_Early_Repayment__c" "Discount RTR From Early Repayment",
  iff(
    "cmbls__Open_Balance__c" > 0
    AND "cmbls__Status__c" != 'Write Off'
    AND "cmbls__Funded_Date__c" IS NOT NULL,
    "cmbls__Open_Balance__c",
    NULL
  ) "Open Balance",
  "cmbls__Status__c" "Repayment Status",
  TO_DOUBLE("Pacing_Per__c") "Pacing"
  //,"Num_Days_Past_Due__c" "Days Past Due"
,
  "cmbls__Total_Write_Off__c" "Total Write Off"
  //PAYMNET FACTS
,
  "SUM_Failed Payment" "Total Failed Paymnets",
  "cmbls__First_Payment_Date__c" "First Payment Date",
  to_date("MIN_Failed Payment Date") "First Failed Paymnet Date",
  to_date("MAX_Failed Payment Date") "Last Failed Paymnet Date",
  to_date("cmbls__Next_Payment_Due_Date__c") as "Next Paymnet Due Date"
  // Record Ids
,
  "Id" "OpportunityId",
  "Id_Application" "ApplicationId",
  "AccountId",
  "Id_RHS1" "RepaymnetId"
  //Appended Fields
,
  IFF(
    ZEROIFNULL("Discount_Early_Repayment__c") > 0,
    1,
    0
  ) "Is Early Repayment Executed",
  iff("Funded_Date__c" IS NOT NULL, 1, 0) "Is Funded",
  Sum("Is Funded") OVER (
    partition BY
      "AccountId"
    ORDER BY
      "AccountId" ASC,
      "Funded_Date__c" ASC
  ) AS "Funded Sequence",
  IFF(
    "Type" != 'New Customer'
    AND "Funded_Date__c" IS NOT NULL,
    1,
    0
  ) "Is Repeat Deal",
  "Early_Repayment_Adjustment_Collected__c" "Early Repayment Total Collected",
  iff("cmbls__Status__c" = 'Write Off', 1, 0) "Is Write Off",
  --NULLIF("Discount_Early_Repayment__c" / (NULLIF("Repayment_Amount__c" - "Funded_Amount__c",0)),0) AS "Early Repayment Reduced % of Original Margin",
  ("Repayment_Amount__c" - "Funded_Amount__c") "Original Margin",
  NULLIFZERO(
    iff(
      "Credit Score Lookup" is null,
      "creditchecker__Average_Score__c_RHS",
      "Credit Score Lookup"
    )
  ) "Primary Owner FICO",
  "Last_Payment_Received_Date__c" "Last Payment Received Date",
  DATEDIFF(
    'days',
    "Funded_Date__c",
    "Last_Payment_Received_Date__c"
  ) "Duration Days",
  iff(
    "Funded_Date__c" IS NOT NULL,
    "Origination_Fee__c",
    0
  ) "Origination Fee Assessed",
  iff(
    "cmbls__Open_Balance__c" > 0
    AND "cmbls__Status__c" != 'Write Off'
    AND "cmbls__Funded_Date__c" IS NOT NULL,
    "cmbls__Principal_Balance_Amount__c",
    NULL
  ) "Open Principal Balance",
  iff(
    "cmbls__Open_Balance__c" > 0
    AND "cmbls__Status__c" != 'Write Off'
    AND "cmbls__Funded_Date__c" IS NOT NULL,
    1,
    0
  ) "Is Active Unit",
  "cmbls__Write_Off__c" "Write Off Principal",
  "OwnerId" "Sales Rep Id",
  "Lead_Vintage__c",
  "Monthly_Rate_Factor__c",
  "Sales Rep Name",
  "New Sales Rep Team Member" "Original Sales Rep",
  "Renew Sales Rep Team Member" "Original Renewal Rep",
  iff(
    "Funded_Date__c" IS NOT NULL,
    ("Monthly_Rate_Factor__c" -1) * "Funded Amount",
    NULL
  ) "Monthly Margin",
  "Submission_Type__c" "Submission Type",
  underwriter_alias."Underwriter Name",
  partner_alias."Partner Name",
  processor_alias."Processor Name",
  "cmbls__Amount_Paid_Interest__c" + "cmbls__Amount_Paid_Principal__c" "Total RTR Amount Paid",
  "Payment_Amount__c" "Weekly Payment Amount - Contractual",
  "cmbls__Payment_Amount__c" "Weekly Payment Amount - Current",
  "Count_of_Expected_Payments__c" "Count of Expected Payments",
  "Weekly Payment Amount - Contractual" * "Count of Expected Payments" "Total Expected Payments - Contractual",
  "Weekly Payment Amount - Current" * "Count of Expected Payments" "Total Expected Payments - Current"
  //, "Borrower_Refunded_Amount__c" "Borrower Refunded Amount"
  //, "Collected_Installment_Payments__c" "Collected Installment Payments"
  //, "Collected Installment Payments"-"Borrower Refunded Amount" "Total RTR Amount Paid Validation"
,
  "Auto-Approval",
  "Opportunity_Num_Contact_Roles__c" "Number of Applicants",
  "Approval_Available_Amount__c" "Approval Available Amount",
  "StageName" "Deal Stage",
  LAST_VALUE("ApplicationId") IGNORE NULLS OVER (
    PARTITION BY
      "AccountId"
    ORDER BY
      "Application Date" ROWS BETWEEN UNBOUNDED PRECEDING
      AND CURRENT ROW
  ) AS "Previous ApplicationId",
  //TURN TIME DAYS
  DATEDIFF(
    'days',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    ),
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Approval_Date__c")
  ) "App to Approval Days",
  DATEDIFF(
    'hours',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    ),
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Approval_Date__c")
  ) "App to Approval Hours",
  DATEDIFF(
    'days',
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Approval_Date__c"),
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Funded_Date__c")
  ) "Approve to Funded",
  DATEDIFF(
    'days',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    ),
    CONVERT_TIMEZONE('UTC', 'America/Los_Angeles', "Funded_Date__c")
  ) "App to Funded",
  DATEDIFF(
    'hours',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    ),
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Processing_Date__c"
    )
  ) "App to Processed Hours",
  DATEDIFF(
    'hours',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Application_In_Date__c"
    ),
    "UW Decision Date"
  ) "App to Decision Hours",
  DATEDIFF(
    'hours',
    CONVERT_TIMEZONE(
      'UTC',
      'America/Los_Angeles',
      "Contract_In_Date__c"
    ),
    "Due_Diligence_Date__c"
  ) "Contract In to Due Diligence"
from
  "Opp_w_HistoryicalCredit"
  //GET UW NAME
  LEFT JOIN (
    SELECT
      "Id" AS "Underwriter Id",
      "Name" AS "Underwriter Name"
    FROM
      SFDC.STAGE.USER
  ) AS underwriter_alias ON "Opp_w_HistoryicalCredit"."Underwriter__c" = underwriter_alias."Underwriter Id"
  //GET PROCESSOR NAME
  LEFT JOIN (
    SELECT
      "Id" AS "Processor Id",
      "Name" AS "Processor Name"
    FROM
      SFDC.STAGE.USER
  ) AS processor_alias ON "Opp_w_HistoryicalCredit"."Processor__c" = processor_alias."Processor Id"
  //GET Partner NAME
  LEFT JOIN (
    SELECT
      "Id" AS "Partner Id",
      "Name" AS "Partner Name"
    FROM
      SFDC.STAGE.ACCOUNT
  ) AS partner_alias ON "Opp_w_HistoryicalCredit"."Strategic_Partner__c" = partner_alias."Partner Id"
WHERE
  "Application_In_Date__c" IS NOT NULL;