ANALYTICS.INFORMATION_SCHEMAcreate or replace view SFDC.PUBLIC.CAMPAIGN_INFLUENCE_V2(
	"Id",
	"IsDeleted",
	"CreatedDate",
	"CreatedById",
	"LastModifiedDate",
	"LastModifiedById",
	"SystemModstamp",
	"OpportunityId",
	"CampaignId",
	"ContactId",
	"Influence",
	"ModelId",
	"RevenueShare",
	"Opp_Id",
	"Type",
	"OppCreatedDate",
	"CampaignId_StartDate",
	"CampaignName",
	"StartDate",
	"Valid Opportunities",
	RNO,
	"Campaigns",
	"First Campaign Name",
	"Last Campaign Name",
	"Id_RHS",
	"IsDeleted_RHS",
	"Name",
	"ParentId",
	"Type_RHS",
	"RecordTypeId",
	"Status",
	"StartDate_RHS",
	"EndDate",
	"ExpectedRevenue",
	"BudgetedCost",
	"ActualCost",
	"ExpectedResponse",
	"NumberSent",
	"IsActive",
	"Description",
	"CampaignImageId",
	"TenantId",
	"NumberOfLeads",
	"NumberOfConvertedLeads",
	"NumberOfContacts",
	"NumberOfResponses",
	"NumberOfOpportunities",
	"NumberOfWonOpportunities",
	"AmountAllOpportunities",
	"AmountWonOpportunities",
	"TotalEmailsDelivered",
	"UniqueEmailOpens",
	"UniqueEmailTrackedLinkClicks",
	"TotalFormViews",
	"TotalFormSubmissions",
	"UniqueMarketingLinkClicks",
	"TotalLandingPageViews",
	"TotalLandingPageFormSubmissions",
	"HierarchyNumberOfLeads",
	"HierarchyNumberOfConvertedLeads",
	"HierarchyNumberOfContacts",
	"HierarchyNumberOfResponses",
	"HierarchyNumberOfOpportunities",
	"HierarchyNumberOfWonOpportunities",
	"HierarchyAmountAllOpportunities",
	"HierarchyAmountWonOpportunities",
	"HierarchyActualCost",
	"HierarchyTotalEmailsDelivered",
	"HierarchyUniqueEmailOpens",
	"HierarchyUniqueEmailTrackedLinkClicks",
	"HierarchyTotalFormViews",
	"HierarchyTotalFormSubmissions",
	"HierarchyUniqueMarketingLinkClicks",
	"HierarchyTotalLandingPageViews",
	"HierarchyTotalLandingPageFormSubmissions",
	"OwnerId",
	"CreatedDate_RHS",
	"CreatedById_RHS",
	"LastModifiedDate_RHS",
	"LastModifiedById_RHS",
	"SystemModstamp_RHS",
	"LastActivityDate",
	"LastViewedDate",
	"LastReferencedDate",
	"UserRecordAccessId",
	"CampaignMemberRecordTypeId",
	"UTM_Campaign__c",
	"UTM_Content__c",
	"UTM_Medium__c",
	"UTM_Source__c",
	"UTM_Term__c",
	"pi__Pardot_Campaign_Id__c",
	"pi__Pardot_Has_Dependencies__c",
	"Phone__c",
	"Num_Opened__c",
	"Sub_Type__c",
	"Abbreviation__c",
	"Per_Opened__c",
	"Num_Clicked__c",
	"Per_Clicked__c",
	"Num_Bounced__c",
	"Per_Bounced__c",
	"Segment__c",
	"Source_Account__c",
	"Id_ParentCampaignId",
	"Parent Campaign Name",
	"Id_Opportunity",
	"Is Application In",
	"Is Approval",
	"Approved Dollars",
	"Is Funded",
	"Funded Volume"
) as
    -- comment = '<comment>'
 WITH
  "OppCreatedDate" AS (
    SELECT
      "Id" AS "Opp_Id",
      "Type",
      "CreatedDate" AS "OppCreatedDate"
    FROM
      "SFDC"."STAGE"."OPPORTUNITY"
  ),
  "InfluencewithOpp" AS (
    SELECT
      LHS."Id",
LHS."IsDeleted",
LHS."CreatedDate",
LHS."CreatedById",
LHS."LastModifiedDate",
LHS."LastModifiedById",
LHS."SystemModstamp",
LHS."OpportunityId",
LHS."CampaignId",
LHS."ContactId",
LHS."Influence",
LHS."ModelId",
LHS."RevenueShare",


      
      RHS."Opp_Id",
      RHS."Type",
      RHS."OppCreatedDate"
    FROM
      "SFDC"."STAGE"."CAMPAIGNINFLUENCE" LHS
      LEFT OUTER JOIN "OppCreatedDate" RHS ON LHS."OpportunityId" = RHS."Opp_Id"
  ),
  "CampaignStartDate" AS (
    SELECT
      "Id" AS "CampaignId_StartDate",
      "Name" AS "CampaignName",
      "StartDate"
    FROM
      "SFDC"."STAGE"."CAMPAIGN"
  ),
  "Parent Campaign" AS (
    SELECT
      "Id" AS "Id_ParentCampaignId",
      "Name" AS "Parent Campaign Name"
    FROM
      "SFDC"."STAGE"."CAMPAIGN"
  ),
  "CampaignInfluence_w_Campaign" AS (
    SELECT
      LHS.*,
      RHS."CampaignId_StartDate",
      RHS."CampaignName",
      RHS."StartDate"
    FROM
      "InfluencewithOpp" LHS
      INNER JOIN "CampaignStartDate" RHS ON LHS."CampaignId" = RHS."CampaignId_StartDate"
  ),
  "Opportunity_op0" AS (
    SELECT
      "Id" AS "Id",
      "IsDeleted" AS "IsDeleted",
      "AccountId" AS "AccountId",
      "RecordTypeId" AS "RecordTypeId",
      "Name" AS "Name",
      "Description" AS "Description",
      "StageName" AS "StageName",
      "Amount" AS "Amount",
      "Probability" AS "Probability",
      "CloseDate" AS "CloseDate",
      "Type" AS "Type",
      "NextStep" AS "NextStep",
      "LeadSource" AS "LeadSource",
      "IsClosed" AS "IsClosed",
      "IsWon" AS "IsWon",
      "ForecastCategory" AS "ForecastCategory",
      "ForecastCategoryName" AS "ForecastCategoryName",
      "CampaignId" AS "CampaignId",
      "HasOpportunityLineItem" AS "HasOpportunityLineItem",
      "Pricebook2Id" AS "Pricebook2Id",
      "OwnerId" AS "OwnerId",
      "CreatedDate" AS "CreatedDate",
      "CreatedById" AS "CreatedById",
      "LastModifiedDate" AS "LastModifiedDate",
      "LastModifiedById" AS "LastModifiedById",
      "SystemModstamp" AS "SystemModstamp",
      "LastActivityDate" AS "LastActivityDate",
      "PushCount" AS "PushCount",
      "LastStageChangeDate" AS "LastStageChangeDate",
      "Fiscal" AS "Fiscal",
      "ContactId" AS "ContactId",
      "LastViewedDate" AS "LastViewedDate",
      "LastReferencedDate" AS "LastReferencedDate",
      "UserRecordAccessId" AS "UserRecordAccessId",
      "SyncedQuoteId" AS "SyncedQuoteId",
      "ContractId" AS "ContractId",
      "HasOpenActivity" AS "HasOpenActivity",
      "HasOverdueTask" AS "HasOverdueTask",
      "LastAmountChangedHistoryId" AS "LastAmountChangedHistoryId",
      "LastCloseDateChangedHistoryId" AS "LastCloseDateChangedHistoryId",
      "Budget_Confirmed__c" AS "Budget_Confirmed__c",
      "Discovery_Completed__c" AS "Discovery_Completed__c",
      "ROI_Analysis_Completed__c" AS "ROI_Analysis_Completed__c",
      "Use_of_Funds_Description__c" AS "Use_of_Funds_Description__c",
      "Stage_Reason__c" AS "Stage_Reason__c",
      "Agreement_Number__c" AS "Agreement_Number__c",
      "Maximum_Approval__c" AS "Maximum_Approval__c",
      "Lender_Account__c" AS "Lender_Account__c",
      "Approval_Expiration_Date__c" AS "Approval_Expiration_Date__c",
      "Date_on_Docs__c" AS "Date_on_Docs__c",
      "Funded_Amount__c" AS "Funded_Amount__c",
      "Repayment_Amount__c" AS "Repayment_Amount__c",
      "Rate_Factor__c" AS "Rate_Factor__c",
      "Payment_Frequency__c" AS "Payment_Frequency__c",
      "Number_of_Payments__c" AS "Number_of_Payments__c",
      "Origination_Fee__c" AS "Origination_Fee__c",
      "Application_In_Date__c" AS "Application_In_Date__c",
      "Credit_Review_Date__c" AS "Credit_Review_Date__c",
      "Approval_Date__c" AS "Approval_Date__c",
      "Offer_Out_Date__c" AS "Offer_Out_Date__c",
      "Offer_In_Date__c" AS "Offer_In_Date__c",
      "Contract_Out_Date__c" AS "Contract_Out_Date__c",
      "Contract_In_Date__c" AS "Contract_In_Date__c",
      "Due_Diligence_Date__c" AS "Due_Diligence_Date__c",
      "Funded_Date__c" AS "Funded_Date__c",
      "Pended_Date__c" AS "Pended_Date__c",
      "Declined_Date__c" AS "Declined_Date__c",
      "Approved_Amount_Disbursed__c" AS "Approved_Amount_Disbursed__c",
      "Repayment_Status__c" AS "Repayment_Status__c",
      "Payment_Amount__c" AS "Payment_Amount__c",
      "Retrieval_Rate__c" AS "Retrieval_Rate__c",
      "Monthly_Rate_Factor__c" AS "Monthly_Rate_Factor__c",
      "McaApp__Activities_in_Current_Stage__c" AS "McaApp__Activities_in_Current_Stage__c",
      "McaApp__Activity_Count__c" AS "McaApp__Activity_Count__c",
      "McaApp__Agreement_Requested_Date_Time__c" AS "McaApp__Agreement_Requested_Date_Time__c",
      "McaApp__Agreement_Requested__c" AS "McaApp__Agreement_Requested__c",
      "McaApp__Agreement_Sent_Date_Time__c" AS "McaApp__Agreement_Sent_Date_Time__c",
      "McaApp__Agreement_Sent__c" AS "McaApp__Agreement_Sent__c",
      "McaApp__Agreement_Signed_Date_Time__c" AS "McaApp__Agreement_Signed_Date_Time__c",
      "McaApp__Agreement_Signed__c" AS "McaApp__Agreement_Signed__c",
      "McaApp__Amount_Requested__c" AS "McaApp__Amount_Requested__c",
      "McaApp__App_Received_Date__c" AS "McaApp__App_Received_Date__c",
      "McaApp__App_Received__c" AS "McaApp__App_Received__c",
      "McaApp__App_Sent_Date__c" AS "McaApp__App_Sent_Date__c",
      "McaApp__App_Sent__c" AS "McaApp__App_Sent__c",
      "McaApp__Application_In_Date_Time__c" AS "McaApp__Application_In_Date_Time__c",
      "McaApp__Application_In__c" AS "McaApp__Application_In__c",
      "McaApp__Application_Missing_Info_Date_Time__c" AS "McaApp__Application_Missing_Info_Date_Time__c",
      "McaApp__Application_Missing_Info__c" AS "McaApp__Application_Missing_Info__c",
      "McaApp__Application_Sent_Date_Time__c" AS "McaApp__Application_Sent_Date_Time__c",
      "McaApp__Application_Sent__c" AS "McaApp__Application_Sent__c",
      "McaApp__Application__c" AS "McaApp__Application__c",
      "McaApp__ApprovedStage__c" AS "McaApp__ApprovedStage__c",
      "McaApp__Approved_Date_Time__c" AS "McaApp__Approved_Date_Time__c",
      "McaApp__Approved_Date__c" AS "McaApp__Approved_Date__c",
      "McaApp__Approved__c" AS "McaApp__Approved__c",
      "McaApp__Average_Amex_Volume__c" AS "McaApp__Average_Amex_Volume__c",
      "McaApp__Average_Daily_Balance__c" AS "McaApp__Average_Daily_Balance__c",
      "McaApp__Avg_Number_Bank_Deposits__c" AS "McaApp__Avg_Number_Bank_Deposits__c",
      "McaApp__Bank_Name__c" AS "McaApp__Bank_Name__c",
      "McaApp__Bank_Program__c" AS "McaApp__Bank_Program__c",
      "McaApp__Batches__c" AS "McaApp__Batches__c",
      "McaApp__Buy_Rate__c" AS "McaApp__Buy_Rate__c",
      "McaApp__Checklist_Notes__c" AS "McaApp__Checklist_Notes__c",
      "McaApp__Chosen_Offer__c" AS "McaApp__Chosen_Offer__c",
      "McaApp__Closed_Lost_Date_Time__c" AS "McaApp__Closed_Lost_Date_Time__c",
      "McaApp__Closed_Lost__c" AS "McaApp__Closed_Lost__c",
      "McaApp__Closed_Stip_Count__c" AS "McaApp__Closed_Stip_Count__c",
      "McaApp__Commission_Engine_Check__c" AS "McaApp__Commission_Engine_Check__c",
      "McaApp__Commission_Percentage__c" AS "McaApp__Commission_Percentage__c",
      "McaApp__Commissions_Payable_External__c" AS "McaApp__Commissions_Payable_External__c",
      "McaApp__Commissions_Payable_Internal__c" AS "McaApp__Commissions_Payable_Internal__c",
      "McaApp__Contract_Requested_Date__c" AS "McaApp__Contract_Requested_Date__c",
      "McaApp__Contract_Signed__c" AS "McaApp__Contract_Signed__c",
      "McaApp__CountAttachment__c" AS "McaApp__CountAttachment__c",
      "McaApp__Created_Upon_Convert__c" AS "McaApp__Created_Upon_Convert__c",
      "McaApp__Credit_Card_Sales__c" AS "McaApp__Credit_Card_Sales__c",
      "McaApp__Credit_Score__c" AS "McaApp__Credit_Score__c",
      "McaApp__Current_Balance_Date__c" AS "McaApp__Current_Balance_Date__c",
      "McaApp__Current_Balance__c" AS "McaApp__Current_Balance__c",
      "McaApp__Date_Contract_Signed__c" AS "McaApp__Date_Contract_Signed__c",
      "McaApp__Date_Funded__c" AS "McaApp__Date_Funded__c",
      "McaApp__Days_in_Current_Stage__c" AS "McaApp__Days_in_Current_Stage__c",
      "McaApp__Days_lead_to_funding__c" AS "McaApp__Days_lead_to_funding__c",
      "McaApp__Deal_Entry_Wizard_Check__c" AS "McaApp__Deal_Entry_Wizard_Check__c",
      "McaApp__Deal_Type__c" AS "McaApp__Deal_Type__c",
      "McaApp__Declined_Date_Time__c" AS "McaApp__Declined_Date_Time__c",
      "McaApp__Declined__c" AS "McaApp__Declined__c",
      "McaApp__Deposits_Minus_Deductions__c" AS "McaApp__Deposits_Minus_Deductions__c",
      "McaApp__Display_on_Renewal_Management__c" AS "McaApp__Display_on_Renewal_Management__c",
      "McaApp__Email_Open_Stips__c" AS "McaApp__Email_Open_Stips__c",
      "McaApp__Email__c" AS "McaApp__Email__c",
      "McaApp__Estimated_Renewal_Date__c" AS "McaApp__Estimated_Renewal_Date__c",
      "McaApp__Factor_Rate__c" AS "McaApp__Factor_Rate__c",
      "McaApp__FundedStage__c" AS "McaApp__FundedStage__c",
      "McaApp__Funded_Date_Time__c" AS "McaApp__Funded_Date_Time__c",
      "McaApp__Funded_Notes__c" AS "McaApp__Funded_Notes__c",
      "McaApp__Funded_Payback__c" AS "McaApp__Funded_Payback__c",
      "McaApp__Funded__c" AS "McaApp__Funded__c",
      "McaApp__Funding_Amount__c" AS "McaApp__Funding_Amount__c",
      "McaApp__Generic_Search__c" AS "McaApp__Generic_Search__c",
      "McaApp__Gross_monthly_Sales__c" AS "McaApp__Gross_monthly_Sales__c",
      "McaApp__Has_Unmatched_Documents__c" AS "McaApp__Has_Unmatched_Documents__c",
      "McaApp__Holdback_Percentage__c" AS "McaApp__Holdback_Percentage__c",
      "McaApp__ISO_Sales_Rep__c" AS "McaApp__ISO_Sales_Rep__c",
      "McaApp__ISO__c" AS "McaApp__ISO__c",
      "McaApp__Last_Activity_Comments__c" AS "McaApp__Last_Activity_Comments__c",
      "McaApp__Last_Activity_Date_Time__c" AS "McaApp__Last_Activity_Date_Time__c",
      "McaApp__Last_Activity_Stage__c" AS "McaApp__Last_Activity_Stage__c",
      "McaApp__Last_Activity_Type__c" AS "McaApp__Last_Activity_Type__c",
      "McaApp__Last_Activity_User__c" AS "McaApp__Last_Activity_User__c",
      "McaApp__Last_Stage_Change_Date__c" AS "McaApp__Last_Stage_Change_Date__c",
      "McaApp__Lead_Created_Date__c" AS "McaApp__Lead_Created_Date__c",
      "McaApp__Lead_Score_at_Conversion__c" AS "McaApp__Lead_Score_at_Conversion__c",
      "McaApp__MapFromLeadDescription__c" AS "McaApp__MapFromLeadDescription__c",
      "McaApp__Markup__c" AS "McaApp__Markup__c",
      "McaApp__Min_Monthly_Deposits__c" AS "McaApp__Min_Monthly_Deposits__c",
      "McaApp__Months_Since_Funding__c" AS "McaApp__Months_Since_Funding__c",
      "McaApp__NDBs_avg__c" AS "McaApp__NDBs_avg__c",
      "McaApp__NSFs_avg__c" AS "McaApp__NSFs_avg__c",
      "McaApp__Net_Funded_Amount__c" AS "McaApp__Net_Funded_Amount__c",
      "McaApp__NewInsert__c" AS "McaApp__NewInsert__c",
      "McaApp__Next_Activity_Assigned_To__c" AS "McaApp__Next_Activity_Assigned_To__c",
      "McaApp__Next_Activity_Comments__c" AS "McaApp__Next_Activity_Comments__c",
      "McaApp__Next_Activity_Date__c" AS "McaApp__Next_Activity_Date__c",
      "McaApp__Next_Activity_Type__c" AS "McaApp__Next_Activity_Type__c",
      "McaApp__Next_Opportunity__c" AS "McaApp__Next_Opportunity__c",
      "McaApp__Next_Step_Due_Date__c" AS "McaApp__Next_Step_Due_Date__c",
      "McaApp__Next_Step_Value__c" AS "McaApp__Next_Step_Value__c",
      "McaApp__Number_of_Funders__c" AS "McaApp__Number_of_Funders__c",
      "McaApp__Number_of_Owners__c" AS "McaApp__Number_of_Owners__c",
      "McaApp__Number_of_Submission__c" AS "McaApp__Number_of_Submission__c",
      "McaApp__Number_of_offers__c" AS "McaApp__Number_of_offers__c",
      "McaApp__Open_Stip_Count__c" AS "McaApp__Open_Stip_Count__c",
      "McaApp__Origination_Fee__c" AS "McaApp__Origination_Fee__c",
      "McaApp__Origination_Fees_Payable_External__c" AS "McaApp__Origination_Fees_Payable_External__c",
      "McaApp__Origination_Fees_Payable_Internal__c" AS "McaApp__Origination_Fees_Payable_Internal__c",
      "McaApp__Owner_1_Ownership__c" AS "McaApp__Owner_1_Ownership__c",
      "McaApp__Owner_1__c" AS "McaApp__Owner_1__c",
      "McaApp__Owner_2_Credit_Score__c" AS "McaApp__Owner_2_Credit_Score__c",
      "McaApp__Owner_2_Ownership__c" AS "McaApp__Owner_2_Ownership__c",
      "McaApp__Owner_2__c" AS "McaApp__Owner_2__c",
      "McaApp__Owner_3_Credit_Score__c" AS "McaApp__Owner_3_Credit_Score__c",
      "McaApp__Owner_3_Ownership__c" AS "McaApp__Owner_3_Ownership__c",
      "McaApp__Owner_3__c" AS "McaApp__Owner_3__c",
      "McaApp__Owner_4_Credit_Score__c" AS "McaApp__Owner_4_Credit_Score__c",
      "McaApp__Owner_4_Ownership__c" AS "McaApp__Owner_4_Ownership__c",
      "McaApp__Owner_4__c" AS "McaApp__Owner_4__c",
      "McaApp__PaidImage__c" AS "McaApp__PaidImage__c",
      "McaApp__Paid_Image__c" AS "McaApp__Paid_Image__c",
      "McaApp__Paid_Percentage__c" AS "McaApp__Paid_Percentage__c",
      "McaApp__Payback_Amount__c" AS "McaApp__Payback_Amount__c",
      "McaApp__Payment_Amount__c" AS "McaApp__Payment_Amount__c",
      "McaApp__Payoff_Amount__c" AS "McaApp__Payoff_Amount__c",
      "McaApp__Previous_Opportunity1__c" AS "McaApp__Previous_Opportunity1__c",
      "McaApp__Processed_Minus_Amex__c" AS "McaApp__Processed_Minus_Amex__c",
      "McaApp__Progress_Bar_Icon__c" AS "McaApp__Progress_Bar_Icon__c",
      "McaApp__Progress_Bar__c" AS "McaApp__Progress_Bar__c",
      "McaApp__PushCount__c" AS "McaApp__PushCount__c",
      "McaApp__Qualified__c" AS "McaApp__Qualified__c",
      "McaApp__Rate__c" AS "McaApp__Rate__c",
      "McaApp__Reason_Lost__c" AS "McaApp__Reason_Lost__c",
      "McaApp__Remove_from_Renewal_Management__c" AS "McaApp__Remove_from_Renewal_Management__c",
      "McaApp__Renewal_Agent__c" AS "McaApp__Renewal_Agent__c",
      "McaApp__Renewal_Eligibility_Days_from_funding__c" AS "McaApp__Renewal_Eligibility_Days_from_funding__c",
      "McaApp__Renewal_Eligibility_Percent__c" AS "McaApp__Renewal_Eligibility_Percent__c",
      "McaApp__Renewal_Notes__c" AS "McaApp__Renewal_Notes__c",
      "McaApp__Renewal_Prospecting_Date_Time__c" AS "McaApp__Renewal_Prospecting_Date_Time__c",
      "McaApp__Renewal_Prospecting__c" AS "McaApp__Renewal_Prospecting__c",
      "McaApp__Renewal_Requested_Date_Time__c" AS "McaApp__Renewal_Requested_Date_Time__c",
      "McaApp__Renewal_Requested__c" AS "McaApp__Renewal_Requested__c",
      "McaApp__Reply_to_Address__c" AS "McaApp__Reply_to_Address__c",
      "McaApp__Schedule__c" AS "McaApp__Schedule__c",
      "McaApp__Sender_s_Name__c" AS "McaApp__Sender_s_Name__c",
      "McaApp__Set_Opportunity_Status__c" AS "McaApp__Set_Opportunity_Status__c",
      "McaApp__Submission_Counter__c" AS "McaApp__Submission_Counter__c",
      "McaApp__Submission_Notes__c" AS "McaApp__Submission_Notes__c",
      "McaApp__Term_Completed__c" AS "McaApp__Term_Completed__c",
      "McaApp__Term_Months__c" AS "McaApp__Term_Months__c",
      "McaApp__Term_Requested__c" AS "McaApp__Term_Requested__c",
      "McaApp__Total_Attachment_Count__c" AS "McaApp__Total_Attachment_Count__c",
      "McaApp__Total_Commissions_Payable__c" AS "McaApp__Total_Commissions_Payable__c",
      "McaApp__Total_Commissions_Receivable__c" AS "McaApp__Total_Commissions_Receivable__c",
      "McaApp__Total_Daily_Payments__c" AS "McaApp__Total_Daily_Payments__c",
      "McaApp__Total_Loan_Balances__c" AS "McaApp__Total_Loan_Balances__c",
      "McaApp__Total_Monthly_Payment__c" AS "McaApp__Total_Monthly_Payment__c",
      "McaApp__Total_Origination_Fees_Payable__c" AS "McaApp__Total_Origination_Fees_Payable__c",
      "McaApp__Total_Origination_Fees_Receivable__c" AS "McaApp__Total_Origination_Fees_Receivable__c",
      "McaApp__Total_Payables_External__c" AS "McaApp__Total_Payables_External__c",
      "McaApp__Total_Payables_Internal__c" AS "McaApp__Total_Payables_Internal__c",
      "McaApp__Total_Payables__c" AS "McaApp__Total_Payables__c",
      "McaApp__Total_Receivables__c" AS "McaApp__Total_Receivables__c",
      "McaApp__Total_Syndication_Amt__c" AS "McaApp__Total_Syndication_Amt__c",
      "McaApp__Total_Syndications_Fee__c" AS "McaApp__Total_Syndications_Fee__c",
      "McaApp__Transactions__c" AS "McaApp__Transactions__c",
      "McaApp__Underwriting_Date_Time__c" AS "McaApp__Underwriting_Date_Time__c",
      "McaApp__Underwriting__c" AS "McaApp__Underwriting__c",
      "McaApp__Use_of_Proceeds__c" AS "McaApp__Use_of_Proceeds__c",
      "McaApp__WHCDB_Days_since_last_update_or_activity__c" AS "McaApp__WHCDB_Days_since_last_update_or_activity__c",
      "cmbla__ADB_w_Monthly_Payments__c" AS "cmbla__ADB_w_Monthly_Payments__c",
      "cmbla__AdjustedMonthlyCCSales__c" AS "cmbla__AdjustedMonthlyCCSales__c",
      "cmbla__AdjustedMonthlyGrossSales__c" AS "cmbla__AdjustedMonthlyGrossSales__c",
      "cmbla__Bankruptcies__c" AS "cmbla__Bankruptcies__c",
      "cmbla__Business_Hours_In_Stage__c" AS "cmbla__Business_Hours_In_Stage__c",
      "cmbla__Completed_Stips__c" AS "cmbla__Completed_Stips__c",
      "cmbla__Completed__c" AS "cmbla__Completed__c",
      "cmbla__Contact_Home_Phone__c" AS "cmbla__Contact_Home_Phone__c",
      "cmbla__Count_Against_Pipeline__c" AS "cmbla__Count_Against_Pipeline__c",
      "cmbla__CurrentGenerators__c" AS "cmbla__CurrentGenerators__c",
      "cmbla__Date_Applied__c" AS "cmbla__Date_Applied__c",
      "cmbla__Date_Interview__c" AS "cmbla__Date_Interview__c",
      "cmbla__Date_Underwriting__c" AS "cmbla__Date_Underwriting__c",
      "cmbla__Deal_Rating_Details__c" AS "cmbla__Deal_Rating_Details__c",
      "cmbla__Deal_Rating__c" AS "cmbla__Deal_Rating__c",
      "cmbla__Decline_Reason_Notes__c" AS "cmbla__Decline_Reason_Notes__c",
      "cmbla__Decline_Reason__c" AS "cmbla__Decline_Reason__c",
      "cmbla__Decline_Reasons__c" AS "cmbla__Decline_Reasons__c",
      "cmbla__DeliveryInstallationStatus__c" AS "cmbla__DeliveryInstallationStatus__c",
      "cmbla__Factor_Per_Year__c" AS "cmbla__Factor_Per_Year__c",
      "cmbla__File_Number__c" AS "cmbla__File_Number__c",
      "cmbla__Funding_Amount_Override__c" AS "cmbla__Funding_Amount_Override__c",
      "cmbla__Holdback_Amount__c" AS "cmbla__Holdback_Amount__c",
      "cmbla__Hybrid_Daily_Pmt__c" AS "cmbla__Hybrid_Daily_Pmt__c",
      "cmbla__Interview_Completed_Count__c" AS "cmbla__Interview_Completed_Count__c",
      "cmbla__Interview_Score__c" AS "cmbla__Interview_Score__c",
      "cmbla__Interview_Status__c" AS "cmbla__Interview_Status__c",
      "cmbla__Interview_Total_Count__c" AS "cmbla__Interview_Total_Count__c",
      "cmbla__Interviewee__c" AS "cmbla__Interviewee__c",
      "cmbla__Last_Underwriting_Stage_Change__c" AS "cmbla__Last_Underwriting_Stage_Change__c",
      "cmbla__Max_Gross__c" AS "cmbla__Max_Gross__c",
      "cmbla__Max_Holdback__c" AS "cmbla__Max_Holdback__c",
      "cmbla__Max_Monthly_PMT__c" AS "cmbla__Max_Monthly_PMT__c",
      "cmbla__Merchant_Interview_By__c" AS "cmbla__Merchant_Interview_By__c",
      "cmbla__Min_Factor_Per_Month__c" AS "cmbla__Min_Factor_Per_Month__c",
      "cmbla__Open_Positions__c" AS "cmbla__Open_Positions__c",
      "cmbla__OrderNumber__c" AS "cmbla__OrderNumber__c",
      "cmbla__Order_Date__c" AS "cmbla__Order_Date__c",
      "cmbla__Pending_Reason__c" AS "cmbla__Pending_Reason__c",
      "cmbla__Priority_Flag__c" AS "cmbla__Priority_Flag__c",
      "cmbla__Priority__c" AS "cmbla__Priority__c",
      "cmbla__ProgramType__c" AS "cmbla__ProgramType__c",
      "cmbla__Reassign_Underwriter__c" AS "cmbla__Reassign_Underwriter__c",
      "cmbla__Renewal__c" AS "cmbla__Renewal__c",
      "cmbla__Send_Decline_Email__c" AS "cmbla__Send_Decline_Email__c",
      "cmbla__Send_Pend_Email__c" AS "cmbla__Send_Pend_Email__c",
      "cmbla__Services__c" AS "cmbla__Services__c",
      "cmbla__Site_Inspection_Location__c" AS "cmbla__Site_Inspection_Location__c",
      "cmbla__Site_Inspection_Status__c" AS "cmbla__Site_Inspection_Status__c",
      "cmbla__Star_Rating__c" AS "cmbla__Star_Rating__c",
      "cmbla__Stips_Overall__c" AS "cmbla__Stips_Overall__c",
      "cmbla__TaxLiens__c" AS "cmbla__TaxLiens__c",
      "cmbla__Term_Days__c" AS "cmbla__Term_Days__c",
      "cmbla__Terms_To_Offer__c" AS "cmbla__Terms_To_Offer__c",
      "cmbla__Total_Stip_Count__c" AS "cmbla__Total_Stip_Count__c",
      "cmbla__TrackingNumber__c" AS "cmbla__TrackingNumber__c",
      "cmbla__Underwriter_Assignment_Rule_Member__c" AS "cmbla__Underwriter_Assignment_Rule_Member__c",
      "cmbla__Underwriter__c" AS "cmbla__Underwriter__c",
      "cmbla__Underwriting_Notes__c" AS "cmbla__Underwriting_Notes__c",
      "cmbla__Underwriting_Stage__c" AS "cmbla__Underwriting_Stage__c",
      "cmbla__Underwriting_Sub_Stage__c" AS "cmbla__Underwriting_Sub_Stage__c",
      "cmbla__Verifications_Completed__c" AS "cmbla__Verifications_Completed__c",
      "cmbla__Verifications_Total__c" AS "cmbla__Verifications_Total__c",
      "cmbla__Work_Phone__c" AS "cmbla__Work_Phone__c",
      "Count_Against_Pipeline__c" AS "Count_Against_Pipeline__c",
      "Term_Months__c" AS "Term_Months__c",
      "Days_Money_Out__c" AS "Days_Money_Out__c",
      "First_Payment_Date__c" AS "First_Payment_Date__c",
      "Early_Repayment_Structure__c" AS "Early_Repayment_Structure__c",
      "Working_Due_Diligence_Count__c" AS "Working_Due_Diligence_Count__c",
      "Working_Stipulation_Count__c" AS "Working_Stipulation_Count__c",
      "Reporting_Funded_Date__c" AS "Reporting_Funded_Date__c",
      "Installment_Amount_Collected__c" AS "Installment_Amount_Collected__c",
      "Outstanding_Balance__c" AS "Outstanding_Balance__c",
      "Reporting_Application_In_Date__c" AS "Reporting_Application_In_Date__c",
      "Gross_Remittance_Revenue__c" AS "Gross_Remittance_Revenue__c",
      "Pipeline_Amount__c" AS "Pipeline_Amount__c",
      "Repayment_Complete_Date_Time__c" AS "Repayment_Complete_Date_Time__c",
      "Strategic_Partner__c" AS "Strategic_Partner__c",
      "Early_Repayment_Adjustment_Collected__c" AS "Early_Repayment_Adjustment_Collected__c",
      "Miscellaneous_Fee_Amount_Collected__c" AS "Miscellaneous_Fee_Amount_Collected__c",
      "Origination_Fee_Amount_Collected__c" AS "Origination_Fee_Amount_Collected__c",
      "creditchecker__Adverse_Alert__c" AS "creditchecker__Adverse_Alert__c",
      "creditchecker__Average_Score__c" AS "creditchecker__Average_Score__c",
      "creditchecker__Bankruptcy_Count__c" AS "creditchecker__Bankruptcy_Count__c",
      "creditchecker__Charge_Offs_Count__c" AS "creditchecker__Charge_Offs_Count__c",
      "creditchecker__Collections_Count__c" AS "creditchecker__Collections_Count__c",
      "creditchecker__Current_Adverse_Count__c" AS "creditchecker__Current_Adverse_Count__c",
      "creditchecker__Date_Completed__c" AS "creditchecker__Date_Completed__c",
      "creditchecker__Debt_High_Credit__c" AS "creditchecker__Debt_High_Credit__c",
      "creditchecker__DeliveryInstallationStatus__c" AS "creditchecker__DeliveryInstallationStatus__c",
      "creditchecker__Derogatory_Count__c" AS "creditchecker__Derogatory_Count__c",
      "creditchecker__Disputes_Count__c" AS "creditchecker__Disputes_Count__c",
      "creditchecker__Most_Recent_Late__c" AS "creditchecker__Most_Recent_Late__c",
      "creditchecker__Oldest_Date__c" AS "creditchecker__Oldest_Date__c",
      "creditchecker__Previous_Adverse_Count__c" AS "creditchecker__Previous_Adverse_Count__c",
      "creditchecker__Public_Record_Count__c" AS "creditchecker__Public_Record_Count__c",
      "creditchecker__Revolving_Credit_Utilization__c" AS "creditchecker__Revolving_Credit_Utilization__c",
      "creditchecker__Secured_Debt__c" AS "creditchecker__Secured_Debt__c",
      "creditchecker__Total_High_Credit__c" AS "creditchecker__Total_High_Credit__c",
      "creditchecker__Total_Inquiry_Count__c" AS "creditchecker__Total_Inquiry_Count__c",
      "creditchecker__Total_Liability_Balance__c" AS "creditchecker__Total_Liability_Balance__c",
      "creditchecker__Total_Liability_PastDue__c" AS "creditchecker__Total_Liability_PastDue__c",
      "creditchecker__Total_Liability_Payment__c" AS "creditchecker__Total_Liability_Payment__c",
      "creditchecker__Unsecured_Debt__c" AS "creditchecker__Unsecured_Debt__c",
      "Reporting_Funded_Amount__c" AS "Reporting_Funded_Amount__c",
      "Maximum_Repayment_Potential__c" AS "Maximum_Repayment_Potential__c",
      "OBS_Aproximate_Maturity_Date__c" AS "OBS_Aproximate_Maturity_Date__c",
      "Partner_Commission_Potential__c" AS "Partner_Commission_Potential__c",
      "Repayment_Percent__c" AS "Repayment_Percent__c",
      "Partner_Commission_at_Full_Term__c" AS "Partner_Commission_at_Full_Term__c",
      "Funded_Deal_Number__c" AS "Funded_Deal_Number__c",
      "Reporting_Approved__c" AS "Reporting_Approved__c",
      "Cross_Guaranty_Entity__c" AS "Cross_Guaranty_Entity__c",
      "Payoff_Amount__c" AS "Payoff_Amount__c",
      "Parallel_Opportunity__c" AS "Parallel_Opportunity__c",
      "Cross_Guaranty_Guarantor__c" AS "Cross_Guaranty_Guarantor__c",
      "Payoff_Valid_Until__c" AS "Payoff_Valid_Until__c",
      "Repurchase_Scheduled_Amount__c" AS "Repurchase_Scheduled_Amount__c",
      "Bank_Account_Number__c" AS "Bank_Account_Number__c",
      "Bank_Account_Type__c" AS "Bank_Account_Type__c",
      "Bank_Name__c" AS "Bank_Name__c",
      "Bank_Routing_Number__c" AS "Bank_Routing_Number__c",
      "Migrated_to_Fundingo__c" AS "Migrated_to_Fundingo__c",
      "CaseSafe_Id__c" AS "CaseSafe_Id__c",
      "Repayment_Installment_Amount_Collected__c" AS "Repayment_Installment_Amount_Collected__c",
      "Update_Payoff__c" AS "Update_Payoff__c",
      "Reporting_Approval_Date__c" AS "Reporting_Approval_Date__c",
      "Lead_Initial_Create_Date__c" AS "Lead_Initial_Create_Date__c",
      "Initial_Lead_Source__c" AS "Initial_Lead_Source__c",
      "Lead_Vintage__c" AS "Lead_Vintage__c",
      "Reporting_Application_In__c" AS "Reporting_Application_In__c",
      "Reporting_Funded__c" AS "Reporting_Funded__c",
      "Corp_Only__c" AS "Corp_Only__c",
      "SP_Commission_Final__c" AS "SP_Commission_Final__c",
      "SP_Fee_Percent__c" AS "SP_Fee_Percent__c",
      "SP_Est_Commission_at_Full_Term__c" AS "SP_Est_Commission_at_Full_Term__c",
      "SP_Est_Commission_with_Immediate_Payoff__c" AS "SP_Est_Commission_with_Immediate_Payoff__c",
      "Next_Payment_Date__c" AS "Next_Payment_Date__c",
      "Payments_Remaining__c" AS "Payments_Remaining__c",
      "Approved_Monthly_Rate_Factor__c" AS "Approved_Monthly_Rate_Factor__c",
      "Approved_Payment_Frequency__c" AS "Approved_Payment_Frequency__c",
      "Maximum_Approved_Duration__c" AS "Maximum_Approved_Duration__c",
      "Average_Monthly_Cost__c" AS "Average_Monthly_Cost__c",
      "Finance_Charge__c" AS "Finance_Charge__c",
      "Invoiced_Amount__c" AS "Invoiced_Amount__c",
      "Estimated_APR__c" AS "Estimated_APR__c",
      "Net_to_Customer__c" AS "Net_to_Customer__c",
      "Gross_Annual_Sales__c" AS "Gross_Annual_Sales__c",
      "Initial_Payment_Amount__c" AS "Initial_Payment_Amount__c",
      "Initial_Retrieval_Rate__c" AS "Initial_Retrieval_Rate__c",
      "Record_Type_Developer_Name__c" AS "Record_Type_Developer_Name__c",
      "WTD_Term__c" AS "WTD_Term__c",
      "UCC_Filed_Date__c" AS "UCC_Filed_Date__c",
      "Invoice_Discount_Per__c" AS "Invoice_Discount_Per__c",
      "Test_Record__c" AS "Test_Record__c",
      "n2de__DE_Status__c" AS "n2de__DE_Status__c",
      "n2de__Distribution_count__c" AS "n2de__Distribution_count__c",
      "n2de__Distribution_engine_details__c" AS "n2de__Distribution_engine_details__c",
      "n2de__Is_distributed__c" AS "n2de__Is_distributed__c",
      "n2de__Is_reassigned__c" AS "n2de__Is_reassigned__c",
      "n2de__Is_rejected__c" AS "n2de__Is_rejected__c",
      "n2de__Is_trigger_enabled__c" AS "n2de__Is_trigger_enabled__c",
      "n2de__Is_triggered__c" AS "n2de__Is_triggered__c",
      "n2de__Last_distributed__c" AS "n2de__Last_distributed__c",
      "n2de__Last_reassigned__c" AS "n2de__Last_reassigned__c",
      "n2de__Last_rejected__c" AS "n2de__Last_rejected__c",
      "n2de__Time_to_action_mins__c" AS "n2de__Time_to_action_mins__c",
      "Initial_Monthly_Rate_Factor__c" AS "Initial_Monthly_Rate_Factor__c",
      "Fee_Only_Term_Months__c" AS "Fee_Only_Term_Months__c",
      "Initial_Rate_Factor__c" AS "Initial_Rate_Factor__c",
      "Num_Working_Due_Diligences__c" AS "Num_Working_Due_Diligences__c",
      "Envelope_Template_Names__c" AS "Envelope_Template_Names__c",
      "Processing_Date__c" AS "Processing_Date__c",
      "WTD_Factor__c" AS "WTD_Factor__c",
      "SP_Commissionable__c" AS "SP_Commissionable__c",
      "Account_Shipping_State_Code__c" AS "Account_Shipping_State_Code__c",
      "Syndication_Eligible__c" AS "Syndication_Eligible__c",
      "Master_Approval_Expiration__c" AS "Master_Approval_Expiration__c",
      "Approval_Application__c" AS "Approval_Application__c",
      "Per_Paid__c" AS "Per_Paid__c",
      "Average_Monthly_Sales__c" AS "Average_Monthly_Sales__c",
      "Primary_Bank_Account__c" AS "Primary_Bank_Account__c",
      IFF("Application_In_Date__c" is null, NULL, 1) AS "Is Application In",
      IFF("Approval_Date__c" is null, NULL, 1) AS "Is Approval",
      IFF(
        IFF("Approval_Date__c" is null, NULL, 1) = 1,
        "Maximum_Approval__c",
        NULL
      ) AS "Approved Dollars",
      IFF("Funded_Date__c" IS NULL, NULL, 1) AS "Is Funded",
      IFF(
        IFF("Funded_Date__c" IS NULL, NULL, 1) = 1,
        "Funded_Amount__c",
        NULL
      ) AS "Funded Volume"
    FROM
      "SFDC"."STAGE"."OPPORTUNITY"
  ),
  "Campaign_w_Parent" AS (
    SELECT
      LHS.*,
      RHS."Id_ParentCampaignId",
      RHS."Parent Campaign Name"
    FROM
      "SFDC"."STAGE"."CAMPAIGN" LHS
      LEFT OUTER JOIN "Parent Campaign" RHS ON LHS."ParentId" = RHS."Id_ParentCampaignId"
  ),
  "Campaign Influence" AS (
    SELECT
      *
    FROM
      (
        select
          *,
          //valid opportunities ensures opps createad before the campaign start date and not associated with campaign.
          IFF(
            "OppCreatedDate" > "StartDate"
            OR "Type" != 'New Business',
            1,
            0
          ) "Valid Opportunities",
          ROW_NUMBER() OVER (
            PARTITION BY
              "OpportunityId"
            ORDER BY
              "OpportunityId",
              "Influence" DESC,
              "StartDate" DESC
          ) RNO,
          COUNT("CampaignId") OVER (
            PARTITION BY
              "OpportunityId"
          ) "Campaigns",
          FIRST_VALUE("CampaignName") OVER (
            PARTITION BY
              "OpportunityId"
            ORDER BY
              "OpportunityId",
              "StartDate" ASC
          ) "First Campaign Name",
          LAST_VALUE("CampaignName") OVER (
            PARTITION BY
              "OpportunityId"
            ORDER BY
              "OpportunityId",
              "StartDate" ASC
          ) "Last Campaign Name"
        from
          "CampaignInfluence_w_Campaign"
        WHERE
          "Valid Opportunities" = 1
          AND "CampaignName" != 'Salesforce Connector'
      )
    WHERE
      RNO = 1
    ORDER BY
      "OpportunityId",
      "Influence" DESC,
      "Valid Opportunities" DESC,
      "StartDate" ASC
  ),
  "Opportunity" AS (
    SELECT
      "Id" AS "Id_Opportunity",
      "Is Application In",
      "Is Approval",
      "Approved Dollars",
      "Is Funded",
      "Funded Volume"
    FROM
      "Opportunity_op0"
  ),
  "Campaign Influence w Campaign V2" AS (
    SELECT
      LHS.*,
      RHS."Id" AS "Id_RHS",
      RHS."IsDeleted" AS "IsDeleted_RHS",
      RHS."Name",
      RHS."ParentId",
      RHS."Type" AS "Type_RHS",
      RHS."RecordTypeId",
      RHS."Status",
      RHS."StartDate" AS "StartDate_RHS",
      RHS."EndDate",
      RHS."ExpectedRevenue",
      RHS."BudgetedCost",
      RHS."ActualCost",
      RHS."ExpectedResponse",
      RHS."NumberSent",
      RHS."IsActive",
      RHS."Description",
      RHS."CampaignImageId",
      RHS."TenantId",
      RHS."NumberOfLeads",
      RHS."NumberOfConvertedLeads",
      RHS."NumberOfContacts",
      RHS."NumberOfResponses",
      RHS."NumberOfOpportunities",
      RHS."NumberOfWonOpportunities",
      RHS."AmountAllOpportunities",
      RHS."AmountWonOpportunities",
      RHS."TotalEmailsDelivered",
      RHS."UniqueEmailOpens",
      RHS."UniqueEmailTrackedLinkClicks",
      RHS."TotalFormViews",
      RHS."TotalFormSubmissions",
      RHS."UniqueMarketingLinkClicks",
      RHS."TotalLandingPageViews",
      RHS."TotalLandingPageFormSubmissions",
      RHS."HierarchyNumberOfLeads",
      RHS."HierarchyNumberOfConvertedLeads",
      RHS."HierarchyNumberOfContacts",
      RHS."HierarchyNumberOfResponses",
      RHS."HierarchyNumberOfOpportunities",
      RHS."HierarchyNumberOfWonOpportunities",
      RHS."HierarchyAmountAllOpportunities",
      RHS."HierarchyAmountWonOpportunities",
      RHS."HierarchyActualCost",
      RHS."HierarchyTotalEmailsDelivered",
      RHS."HierarchyUniqueEmailOpens",
      RHS."HierarchyUniqueEmailTrackedLinkClicks",
      RHS."HierarchyTotalFormViews",
      RHS."HierarchyTotalFormSubmissions",
      RHS."HierarchyUniqueMarketingLinkClicks",
      RHS."HierarchyTotalLandingPageViews",
      RHS."HierarchyTotalLandingPageFormSubmissions",
      RHS."OwnerId",
      RHS."CreatedDate" AS "CreatedDate_RHS",
      RHS."CreatedById" AS "CreatedById_RHS",
      RHS."LastModifiedDate" AS "LastModifiedDate_RHS",
      RHS."LastModifiedById" AS "LastModifiedById_RHS",
      RHS."SystemModstamp" AS "SystemModstamp_RHS",
      RHS."LastActivityDate",
      RHS."LastViewedDate",
      RHS."LastReferencedDate",
      RHS."UserRecordAccessId",
      RHS."CampaignMemberRecordTypeId",
      RHS."UTM_Campaign__c",
      RHS."UTM_Content__c",
      RHS."UTM_Medium__c",
      RHS."UTM_Source__c",
      RHS."UTM_Term__c",
      RHS."pi__Pardot_Campaign_Id__c",
      RHS."pi__Pardot_Has_Dependencies__c",
      RHS."Phone__c",
      RHS."Num_Opened__c",
      RHS."Sub_Type__c",
      RHS."Abbreviation__c",
      RHS."Per_Opened__c",
      RHS."Num_Clicked__c",
      RHS."Per_Clicked__c",
      RHS."Num_Bounced__c",
      RHS."Per_Bounced__c",
      RHS."Segment__c",
      RHS."Source_Account__c",
      RHS."Id_ParentCampaignId",
      RHS."Parent Campaign Name"
    FROM
      "Campaign Influence" LHS
      RIGHT OUTER JOIN "Campaign_w_Parent" RHS ON LHS."CampaignId" = RHS."Id"
  )
SELECT
  LHS.*,
  RHS."Id_Opportunity",
  RHS."Is Application In",
  RHS."Is Approval",
  RHS."Approved Dollars",
  RHS."Is Funded",
  RHS."Funded Volume"
FROM
  "Campaign Influence w Campaign V2" LHS
  LEFT OUTER JOIN "Opportunity" RHS ON LHS."OpportunityId" = RHS."Id_Opportunity";